// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: io/core/a_rpc_certificates.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PassKit.Grpc.DotNet {

  /// <summary>Holder for reflection information generated from io/core/a_rpc_certificates.proto</summary>
  public static partial class ARpcCertificatesReflection {

    #region Descriptor
    /// <summary>File descriptor for io/core/a_rpc_certificates.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ARpcCertificatesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBpby9jb3JlL2FfcnBjX2NlcnRpZmljYXRlcy5wcm90bxICaW8aHGdvb2ds",
            "ZS9hcGkvYW5ub3RhdGlvbnMucHJvdG8aG2dvb2dsZS9wcm90b2J1Zi9lbXB0",
            "eS5wcm90bxoeaW8vY29tbW9uL2NvbW1vbl9vYmplY3RzLnByb3RvGiBpby9j",
            "ZXJ0aWZpY2F0ZS9jZXJ0aWZpY2F0ZS5wcm90bxoaaW8vY29tbW9uL3BhZ2lu",
            "YXRpb24ucHJvdG8aFmlvL2NvbW1vbi9maWx0ZXIucHJvdG8aLnByb3RvYy1n",
            "ZW4tb3BlbmFwaXYyL29wdGlvbnMvYW5ub3RhdGlvbnMucHJvdG8y6A4KDENl",
            "cnRpZmljYXRlcxLcAQoXZ2V0QXBwbGVDZXJ0aWZpY2F0ZURhdGESFi5pby5Q",
            "YXNzVHlwZUlkZW50aWZpZXIaEy5pby5DZXJ0aWZpY2F0ZURhdGEikwGSQW8S",
            "GkdldCBBcHBsZSBwYXNzIGNlcnRpZmljYXRlGlFHZXRzIHRoZSBjZXJ0aWZp",
            "Y2F0ZSBkYXRhIGZvciBjZXJ0aWZpY2F0ZSB3aXRoIFBhc3MgVHlwZSBJZGVu",
            "dGlmaWVyIHtwYXNzVHlwZUlkfS6C0+STAhsSGS9jZXJ0aWZpY2F0ZS97cGFz",
            "c1R5cGVJZH0S1QEKHGdldENlcnRpZmljYXRlU2lnbmluZ1JlcXVlc3QSFi5n",
            "b29nbGUucHJvdG9idWYuRW1wdHkaHS5pby5DZXJ0aWZpY2F0ZVNpZ25pbmdS",
            "ZXF1ZXN0In6SQUsSJUdldCBDU1IgKENlcnRpZmljYXRlIFNpZ25pbmcgUmVx",
            "dWVzdCkaIkdldHMgYSBDU1IgZm9yIHRoZSBsb2dnZWQgaW4gdXNlci6C0+ST",
            "AioSKC9jZXJ0aWZpY2F0ZS9jZXJ0aWZpY2F0ZV9zaWduaW5nX3JlcXVlc3QS",
            "ogEKE2FkZEFwcGxlQ2VydGlmaWNhdGUSDS5pby5GaWxlQnl0ZXMaEy5pby5D",
            "ZXJ0aWZpY2F0ZURhdGEiZ5JBOxIVQWRkIEFwcGxlIGNlcnRpZmljYXRlGiJV",
            "cGxvYWRzIGFuIEFwcGxlIHBhc3MgY2VydGlmaWNhdGUugtPkkwIjIh4vY2Vy",
            "dGlmaWNhdGUvYXBwbGVfY2VydGlmaWNhdGU6ASoSuwEKFnVwZGF0ZUFwcGxl",
            "Q2VydGlmaWNhdGUSDS5pby5GaWxlQnl0ZXMaEy5pby5DZXJ0aWZpY2F0ZURh",
            "dGEifZJBURIYVXBkYXRlIEFwcGxlIGNlcnRpZmljYXRlGjVVcGRhdGVzIG9y",
            "IHJlbmV3cyBhbiBleGlzdGluZyBBcHBsZSBwYXNzIGNlcnRpZmljYXRlLoLT",
            "5JMCIxoeL2NlcnRpZmljYXRlL2FwcGxlX2NlcnRpZmljYXRlOgEqErsBCh9s",
            "aXN0QXBwbGVDZXJ0aWZpY2F0ZXNEZXByZWNhdGVkEg4uaW8uUGFnaW5hdGlv",
            "bhoTLmlvLkNlcnRpZmljYXRlRGF0YSJxkkFZEilMaXN0IEFwcGxlIHBhc3Mg",
            "Y2VydGlmaWNhdGVzIFtERVBSRUNBVEVEXRosUmV0cmlldmVzIGEgdXNlcnMg",
            "Y2VydGlmaWNhdGVzIFtERVBSRUNBVEVEXS6C0+STAg8SDS9jZXJ0aWZpY2F0",
            "ZXMwARKhAQoVbGlzdEFwcGxlQ2VydGlmaWNhdGVzEgsuaW8uRmlsdGVycxoT",
            "LmlvLkNlcnRpZmljYXRlRGF0YSJkkkE+EhxMaXN0IEFwcGxlIHBhc3MgY2Vy",
            "dGlmaWNhdGVzGh5SZXRyaWV2ZXMgYSB1c2VycyBjZXJ0aWZpY2F0ZXOC0+ST",
            "Ah0iGC9jZXJ0aWZpY2F0ZXMvYXBwbGUvbGlzdDoBKjABEuABCiBjb3VudEFw",
            "cGxlQ2VydGlmaWNhdGVzRGVwcmVjYXRlZBIOLmlvLlBhZ2luYXRpb24aCS5p",
            "by5Db3VudCKgAZJBgQESKkNvdW50IEFwcGxlIHBhc3MgY2VydGlmaWNhdGVz",
            "IFtERVBSRUNBVEVEXRpTUmV0cmlldmVzIHRoZSB0b3RhbCBjb3VudCBvZiBw",
            "YXNzIGNlcnRpZmljYXRlcyBmb3IgdGhlIGxvZ2dlZCBpbiB1c2VyIFtERVBS",
            "RUNBVEVEXS6C0+STAhUSEy9jZXJ0aWZpY2F0ZXMvY291bnQSwQEKFmNvdW50",
            "QXBwbGVDZXJ0aWZpY2F0ZXMSCy5pby5GaWx0ZXJzGgkuaW8uQ291bnQijgGS",
            "QWcSHUNvdW50IEFwcGxlIHBhc3MgY2VydGlmaWNhdGVzGkZSZXRyaWV2ZXMg",
            "dGhlIHRvdGFsIGNvdW50IG9mIHBhc3MgY2VydGlmaWNhdGVzIGZvciB0aGUg",
            "bG9nZ2VkIGluIHVzZXIugtPkkwIeIhkvY2VydGlmaWNhdGVzL2FwcGxlL2Nv",
            "dW50OgEqErQCChlzZW5kTkZDU2lnbmluZ0NyZWRlbnRpYWxzEiAuaW8uTkZD",
            "U2lnbmluZ0NyZWRlbnRpYWxzUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5F",
            "bXB0eSLcAZJBqwESHFNlbmQgTkZDIHNpZ25pbmcgY3JlZGVudGlhbHMaigFT",
            "ZW5kcyB0aGUgTkZDIHNpZ25pbmcgY3JlZGVudGlhbHMgZm9yIGEgY2VydGlm",
            "aWNhdGUgdG8gdGhlIHJlZ2lzdGVyZWQgZW1haWwgYWRkcmVzcyBvZiB0aGUg",
            "dXNlci4gT25seSB3b3JrcyB3aXRoIE5GQyBlbmFibGVkIGNlcnRpZmljYXRl",
            "cy6C0+STAiciIi9jZXJ0aWZpY2F0ZXMvbmZjL2NyZWRlbnRpYWxzL3NlbmQ6",
            "ASpC3wYKEGNvbS5wYXNza2l0LmdycGNaJHN0YXNoLnBhc3NraXQuY29tL2lv",
            "L21vZGVsL3Nkay9nby9pb6oCE1Bhc3NLaXQuR3JwYy5Eb3ROZXSSQY0GEtoB",
            "ChhQYXNzS2l0IENlcnRpZmljYXRlcyBBUEkSQ0FQSSBmb3IgbWFuYWdpbmcg",
            "QXBwbGUgV2FsbGV0IFBhc3MgVHlwZSBJZGVudGlmaWVycyAmIENlcnRpZmlj",
            "YXRlcy4aOGh0dHBzOi8vcGFzc2tpdC5jb20vbGVnYWwvdGVybXMtb2Ytc3Vi",
            "c2NyaXB0aW9uLXNlcnZpY2UvIj8KD1Bhc3NLaXQgU3VwcG9ydBIXaHR0cHM6",
            "Ly9kb2NzLnBhc3NraXQuaW8aE3N1cHBvcnRAcGFzc2tpdC5jb20qAQIyEGFw",
            "cGxpY2F0aW9uL2pzb246EGFwcGxpY2F0aW9uL2pzb25SOQoDMjAwEjIKKFJl",
            "dHVybmVkIHdoZW4gdGhlIHJlcXVlc3QgaXMgc3VjY2Vzc2Z1bC4SBgoEmgIB",
            "B1I0CgM0MDASLQorUmV0dXJuZWQgd2hlbiB3cm9uZyB1c2VyIGlucHV0IGlz",
            "IHByb3ZpZGVkLlIwCgM0MDESKQonUmV0dXJuZWQgd2hlbiB0aGUgdXNlciBp",
            "cyB1bmF1dGhvcml6ZWQuUlAKAzQwMxJJCkdSZXR1cm5lZCB3aGVuIHRoZSB1",
            "c2VyIGRvZXMgbm90IGhhdmUgcGVybWlzc2lvbiB0byBhY2Nlc3MgdGhlIHJl",
            "c291cmNlLlI7CgM0MDQSNAoqUmV0dXJuZWQgd2hlbiB0aGUgcmVzb3VyY2Ug",
            "ZG9lcyBub3QgZXhpc3QuEgYKBJoCAQdSPAoDNTAwEjUKK1JldHVybmVkIHdo",
            "ZW4gdGhlcmUgaXMgYW4gdW5leHBlY3RlZCBlcnJvci4SBgoEmgIBB1JXCgM1",
            "MDMSUApOU2VydmVyIGlzIHVuYXZhaWxhYmxlLiBCYWNrIG9mZiBmb3IgMjUw",
            "bXMgYW5kIHJlcGVhdCByZXF1ZXN0IHVudGlsIHN1Y2Nlc3NmdWwuWj4KPAoK",
            "YXBpS2V5QXV0aBIuCAISGUpXVCBBdXRoZW50aWNhdGlvbiB0b2tlbi4aDUF1",
            "dGhvcml6YXRpb24gAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::PassKit.Grpc.DotNet.CommonObjectsReflection.Descriptor, global::PassKit.Grpc.DotNet.CertificateReflection.Descriptor, global::PassKit.Grpc.DotNet.PaginationReflection.Descriptor, global::PassKit.Grpc.DotNet.FilterReflection.Descriptor, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
