// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: io/scheduler/a_rpc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PassKitGrpcSDK.Scheduler {

  /// <summary>Holder for reflection information generated from io/scheduler/a_rpc.proto</summary>
  public static partial class ARpcReflection {

    #region Descriptor
    /// <summary>File descriptor for io/scheduler/a_rpc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ARpcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhpby9zY2hlZHVsZXIvYV9ycGMucHJvdG8SCXNjaGVkdWxlchocZ29vZ2xl",
            "L2FwaS9hbm5vdGF0aW9ucy5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5",
            "LnByb3RvGi5wcm90b2MtZ2VuLW9wZW5hcGl2Mi9vcHRpb25zL2Fubm90YXRp",
            "b25zLnByb3RvGh5pby9jb21tb24vY29tbW9uX29iamVjdHMucHJvdG8aHGlv",
            "L3NjaGVkdWxlci9zY2hlZHVsZXIucHJvdG8y6xEKCVNjaGVkdWxlchKdAgoT",
            "Y3JlYXRlU2NoZWR1bGluZ0pvYhIYLnNjaGVkdWxlci5TY2hlZHVsaW5nSm9i",
            "GiAuc2NoZWR1bGVyLlNjaGVkdWxpbmdKb2JSZXNwb25zZSLJAYLT5JMCFCIP",
            "L3NjaGVkdWxpbmcvam9iOgEqkkGrAQoPU2NoZWR1bGluZyBKb2JzEhVDcmVh",
            "dGUgU2NoZWR1bGluZyBKb2IaGUNyZWF0ZXMgYSBzY2hlZHVsaW5nIGpvYi5K",
            "MAoDNDAwEikKJ1RoZXJlIGlzIGEgcHJvYmxlbSB3aXRoIHRoZSBpbnB1dCBk",
            "YXRhLko0CgM0MDMSLQorUmV0dXJuZWQgd2hlbiB0aGUgdXNlciBsYWNrcyBh",
            "dXRob3JpemF0aW9uLhKPAgoQZ2V0U2NoZWR1bGluZ0pvYhIGLmlvLklkGhgu",
            "c2NoZWR1bGVyLlNjaGVkdWxpbmdKb2Ii2AGC0+STAhYSFC9zY2hlZHVsaW5n",
            "L2pvYi97aWR9kkG4AQoPU2NoZWR1bGluZyBKb2JzEhJHZXQgU2NoZWR1bGlu",
            "ZyBKb2IaTVJldHJpZXZlcyBhIHNjaGVkdWxpbmcgam9iLiBEZWxldGVkIGpv",
            "YiB3aWxsIHJldHVybiBoaXN0b3J5IGxvZ3Mgb25seSBpZiBhbnkuSiIKAzQw",
            "MxIbChlVc2VyIGxhY2tzIGF1dGhvcml6YXRpb24uSh4KAzQwNBIXChVSZWNv",
            "cmQgd2FzIG5vdCBmb3VuZC4S4wMKE3VwZGF0ZVNjaGVkdWxpbmdKb2ISGC5z",
            "Y2hlZHVsZXIuU2NoZWR1bGluZ0pvYhogLnNjaGVkdWxlci5TY2hlZHVsaW5n",
            "Sm9iUmVzcG9uc2UijwOC0+STAhQaDy9zY2hlZHVsaW5nL2pvYjoBKpJB8QIK",
            "D1NjaGVkdWxpbmcgSm9icxIVVXBkYXRlIFNjaGVkdWxpbmcgSm9iGnhVcGRh",
            "dGVzIGEgc2NoZWR1bGluZyBqb2IuIEZ1bGwgU2NoZWR1bGVySm9iIG9iamVj",
            "dCBpcyByZXF1aXJlZC4gQW4gZW1wdHkgb3IgbnVsbCB2YWx1ZSB3aWxsIG92",
            "ZXJyaWRlIGFueSBleGlzdGluZyB2YWx1ZS5KMAoDNDAwEikKJ1RoZXJlIGlz",
            "IGEgcHJvYmxlbSB3aXRoIHRoZSBpbnB1dCBkYXRhLkoiCgM0MDMSGwoZVXNl",
            "ciBsYWNrcyBhdXRob3JpemF0aW9uLkoeCgM0MDQSFwoVUmVjb3JkIHdhcyBu",
            "b3QgZm91bmQuSlcKAzUwMxJQCk5TZXJ2ZXIgaXMgdW5hdmFpbGFibGUuIEJh",
            "Y2sgb2ZmIGZvciAyNTBtcyBhbmQgcmVwZWF0IHJlcXVlc3QgdW50aWwgc3Vj",
            "Y2Vzc2Z1bC4SiAMKEnBhdGNoU2NoZWR1bGluZ0pvYhIYLnNjaGVkdWxlci5T",
            "Y2hlZHVsaW5nSm9iGiAuc2NoZWR1bGVyLlNjaGVkdWxpbmdKb2JSZXNwb25z",
            "ZSK1AoLT5JMCFDIPL3NjaGVkdWxpbmcvam9iOgEqkkGXAgoPU2NoZWR1bGlu",
            "ZyBKb2JzEhRQYXRjaCBTY2hlZHVsaW5nIEpvYhofUGF0Y2ggdXBkYXRlcyBh",
            "IHNjaGVkdWxpbmcgam9iLkowCgM0MDASKQonVGhlcmUgaXMgYSBwcm9ibGVt",
            "IHdpdGggdGhlIGlucHV0IGRhdGEuSiIKAzQwMxIbChlVc2VyIGxhY2tzIGF1",
            "dGhvcml6YXRpb24uSh4KAzQwNBIXChVSZWNvcmQgd2FzIG5vdCBmb3VuZC5K",
            "VwoDNTAzElAKTlNlcnZlciBpcyB1bmF2YWlsYWJsZS4gQmFjayBvZmYgZm9y",
            "IDI1MG1zIGFuZCByZXBlYXQgcmVxdWVzdCB1bnRpbCBzdWNjZXNzZnVsLhKq",
            "AgoTZGVsZXRlU2NoZWR1bGluZ0pvYhIGLmlvLklkGhYuZ29vZ2xlLnByb3Rv",
            "YnVmLkVtcHR5IvIBgtPkkwIWKhQvc2NoZWR1bGluZy9qb2Ive2lkfZJB0gEK",
            "D1NjaGVkdWxpbmcgSm9icxIVRGVsZXRlIFNjaGVkdWxpbmcgSm9iGlJEZWxl",
            "dGVzIGEgc2NoZWR1bGluZyBqb2IuIEhpc3RvcnkgbG9ncyBhcmUgc3RpbGwg",
            "YXZhaWxhYmxlIGFmdGVyIGRlbGV0aW5nIHRoZSBqb2IuSjQKAzQwMxItCitS",
            "ZXR1cm5lZCB3aGVuIHRoZSB1c2VyIGxhY2tzIGF1dGhvcml6YXRpb24uSh4K",
            "AzQwNBIXChVSZWNvcmQgd2FzIG5vdCBmb3VuZC4SgQIKF2dldFNjaGVkdWxp",
            "bmdKb2JIaXN0b3J5EgYuaW8uSWQaFS5zY2hlZHVsZXIuSm9iSGlzdG9yeSLG",
            "AYLT5JMCGhIYL3NjaGVkdWxpbmcvaGlzdG9yeS97aWR9kkGiAQoNSm9iIEhp",
            "c3RvcmllcxIaR2V0IFNjaGVkdWxpbmcgSm9iIEhpc3RvcnkaMVJldHJpZXZl",
            "cyBhIHNjaGVkdWxpbmcgam9iIGhpc3RvcnkgYnkgdGhlIGxvZyBpZC5KIgoD",
            "NDAzEhsKGVVzZXIgbGFja3MgYXV0aG9yaXphdGlvbi5KHgoDNDA0EhcKFVJl",
            "Y29yZCB3YXMgbm90IGZvdW5kLhKJAgoabGlzdFNjaGVkdWxpbmdKb2JIaXN0",
            "b3JpZXMSFi5zY2hlZHVsZXIuTGlzdFJlcXVlc3QaFS5zY2hlZHVsZXIuSm9i",
            "SGlzdG9yeSK5AYLT5JMCHSIYL3NjaGVkdWxpbmcvaGlzdG9yeS9saXN0OgEq",
            "kkGSAQoNSm9iIEhpc3RvcmllcxIdTGlzdCBTY2hlZHVsaW5nIEpvYiBIaXN0",
            "b3JpZXMaHkxpc3Qgc2NoZWR1bGluZyBqb2IgaGlzdG9yaWVzLkoiCgM0MDMS",
            "GwoZVXNlciBsYWNrcyBhdXRob3JpemF0aW9uLkoeCgM0MDQSFwoVUmVjb3Jk",
            "IHdhcyBub3QgZm91bmQuMAFC3wIKGmNvbS5wYXNza2l0LmdycGMuU2NoZWR1",
            "bGVyWi5zdGFzaC5wYXNza2l0LmNvbS9pby9tb2RlbC9zZGsvZ28vaW8vc2No",
            "ZWR1bGVyqgIYUGFzc0tpdEdycGNTREsuU2NoZWR1bGVykkH0ARLKAQoVUGFz",
            "c0tpdCBTY2hlZHVsZXIgQVBJEjFUaGlzIHByb3RvY29sIHNjaGVkdWxlIHJl",
            "Y3Vyc2l2ZSBvciBvbmUtb2ZmIGpvYnMuGjhodHRwczovL3Bhc3NraXQuY29t",
            "L2xlZ2FsL3Rlcm1zLW9mLXN1YnNjcmlwdGlvbi1zZXJ2aWNlLyI/Cg9QYXNz",
            "S2l0IFN1cHBvcnQSF2h0dHBzOi8vZG9jcy5wYXNza2l0LmlvGhNzdXBwb3J0",
            "QHBhc3NraXQuY29tMgMxLjAqAQIyEGFwcGxpY2F0aW9uL2pzb246EGFwcGxp",
            "Y2F0aW9uL2pzb25iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::PassKitGrpcSDK.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, global::PassKitGrpcSDK.CommonObjectsReflection.Descriptor, global::PassKitGrpcSDK.Scheduler.SchedulerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
