// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: io/core/a_rpc_certificates.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PKIo {

  /// <summary>Holder for reflection information generated from io/core/a_rpc_certificates.proto</summary>
  public static partial class ARpcCertificatesReflection {

    #region Descriptor
    /// <summary>File descriptor for io/core/a_rpc_certificates.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ARpcCertificatesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBpby9jb3JlL2FfcnBjX2NlcnRpZmljYXRlcy5wcm90bxICaW8aHGdvb2ds",
            "ZS9hcGkvYW5ub3RhdGlvbnMucHJvdG8aG2dvb2dsZS9wcm90b2J1Zi9lbXB0",
            "eS5wcm90bxoeaW8vY29tbW9uL2NvbW1vbl9vYmplY3RzLnByb3RvGiBpby9j",
            "ZXJ0aWZpY2F0ZS9jZXJ0aWZpY2F0ZS5wcm90bxoaaW8vY29tbW9uL3BhZ2lu",
            "YXRpb24ucHJvdG8yggYKDENlcnRpZmljYXRlcxKHAQocZ2V0Q2VydGlmaWNh",
            "dGVTaWduaW5nUmVxdWVzdBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRodLmlv",
            "LkNlcnRpZmljYXRlU2lnbmluZ1JlcXVlc3QiMILT5JMCKhIoL2NlcnRpZmlj",
            "YXRlL2NlcnRpZmljYXRlX3NpZ25pbmdfcmVxdWVzdBJkChNhZGRBcHBsZUNl",
            "cnRpZmljYXRlEg0uaW8uRmlsZUJ5dGVzGhMuaW8uQ2VydGlmaWNhdGVEYXRh",
            "IimC0+STAiMiHi9jZXJ0aWZpY2F0ZS9hcHBsZV9jZXJ0aWZpY2F0ZToBKhJn",
            "ChZ1cGRhdGVBcHBsZUNlcnRpZmljYXRlEg0uaW8uRmlsZUJ5dGVzGhMuaW8u",
            "Q2VydGlmaWNhdGVEYXRhIimC0+STAiMaHi9jZXJ0aWZpY2F0ZS9hcHBsZV9j",
            "ZXJ0aWZpY2F0ZToBKhJpChdnZXRBcHBsZUNlcnRpZmljYXRlRGF0YRIWLmlv",
            "LlBhc3NUeXBlSWRlbnRpZmllchoTLmlvLkNlcnRpZmljYXRlRGF0YSIhgtPk",
            "kwIbEhkvY2VydGlmaWNhdGUve3Bhc3NUeXBlSWR9ElUKFWxpc3RBcHBsZUNl",
            "cnRpZmljYXRlcxIOLmlvLlBhZ2luYXRpb24aEy5pby5DZXJ0aWZpY2F0ZURh",
            "dGEiFYLT5JMCDxINL2NlcnRpZmljYXRlczABElAKFmNvdW50QXBwbGVDZXJ0",
            "aWZpY2F0ZXMSDi5pby5QYWdpbmF0aW9uGgkuaW8uQ291bnQiG4LT5JMCFRIT",
            "L2NlcnRpZmljYXRlcy9jb3VudBKEAQoZc2VuZE5GQ1NpZ25pbmdDcmVkZW50",
            "aWFscxIgLmlvLk5GQ1NpZ25pbmdDcmVkZW50aWFsc1JlcXVlc3QaFi5nb29n",
            "bGUucHJvdG9idWYuRW1wdHkiLYLT5JMCJyIiL2NlcnRpZmljYXRlcy9uZmMv",
            "Y3JlZGVudGlhbHMvc2VuZDoBKkI+Cg9pby5wYXNza2l0LlBLaW9aJHN0YXNo",
            "LnBhc3NraXQuY29tL2lvL21vZGVsL3Nkay9nby9pb6oCBFBLSW9iBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::PKIo.CommonObjectsReflection.Descriptor, global::PKIo.CertificateReflection.Descriptor, global::PKIo.PaginationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
