// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: io/single_use_coupons/a_rpc.proto
// </auto-generated>
// Original file comments:
// *
// Single Use Coupon Protocol is suit for cases where the user requires a clean and simple single use coupon for short term coupon campaigns in Apple Wallet and Google Pay.
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PassKitGrpcSDK.SingleUseCoupons {
  public static partial class SingleUseCoupons
  {
    static readonly string __ServiceName = "single_use_coupons.SingleUseCoupons";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> __Marshaller_single_use_coupons_CouponCampaign = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.Id> __Marshaller_io_Id = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.Id.Parser));
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.Pagination> __Marshaller_io_Pagination = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.Pagination.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.Filters> __Marshaller_io_Filters = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.Filters.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.AnalyticsRequest> __Marshaller_io_AnalyticsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.AnalyticsRequest.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaignAnalyticsResponse> __Marshaller_single_use_coupons_CouponCampaignAnalyticsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaignAnalyticsResponse.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> __Marshaller_single_use_coupons_CouponOffer = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequestDeprecated> __Marshaller_single_use_coupons_CouponOffersListRequestDeprecated = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequestDeprecated.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequest> __Marshaller_single_use_coupons_CouponOffersListRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequest.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.SingleUseCoupons.Coupon> __Marshaller_single_use_coupons_Coupon = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.SingleUseCoupons.Coupon.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.SingleUseCoupons.CouponNewExternalIdRequest> __Marshaller_single_use_coupons_CouponNewExternalIdRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.SingleUseCoupons.CouponNewExternalIdRequest.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.SingleUseCoupons.ExternalIdRequest> __Marshaller_single_use_coupons_ExternalIdRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.SingleUseCoupons.ExternalIdRequest.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated> __Marshaller_single_use_coupons_ListRequestDeprecated = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.SingleUseCoupons.ListRequest> __Marshaller_single_use_coupons_ListRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.SingleUseCoupons.ListRequest.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.Count> __Marshaller_io_Count = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.Count.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.PersonRequest> __Marshaller_io_PersonRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.PersonRequest.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.SingleUseCoupons.CampaignCopyRequest> __Marshaller_single_use_coupons_CampaignCopyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.SingleUseCoupons.CampaignCopyRequest.Parser));
    static readonly grpc::Marshaller<global::PassKitGrpcSDK.Strings> __Marshaller_io_Strings = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PassKitGrpcSDK.Strings.Parser));

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign, global::PassKitGrpcSDK.Id> __Method_createCouponCampaign = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign, global::PassKitGrpcSDK.Id>(
        grpc::MethodType.Unary,
        __ServiceName,
        "createCouponCampaign",
        __Marshaller_single_use_coupons_CouponCampaign,
        __Marshaller_io_Id);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> __Method_updateCouponCampaign = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign>(
        grpc::MethodType.Unary,
        __ServiceName,
        "updateCouponCampaign",
        __Marshaller_single_use_coupons_CouponCampaign,
        __Marshaller_single_use_coupons_CouponCampaign);

    static readonly grpc::Method<global::PassKitGrpcSDK.Id, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> __Method_getCouponCampaign = new grpc::Method<global::PassKitGrpcSDK.Id, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getCouponCampaign",
        __Marshaller_io_Id,
        __Marshaller_single_use_coupons_CouponCampaign);

    static readonly grpc::Method<global::PassKitGrpcSDK.Id, global::Google.Protobuf.WellKnownTypes.Empty> __Method_deleteCouponCampaign = new grpc::Method<global::PassKitGrpcSDK.Id, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "deleteCouponCampaign",
        __Marshaller_io_Id,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::PassKitGrpcSDK.Pagination, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> __Method_listCouponCampaignsDeprecated = new grpc::Method<global::PassKitGrpcSDK.Pagination, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "listCouponCampaignsDeprecated",
        __Marshaller_io_Pagination,
        __Marshaller_single_use_coupons_CouponCampaign);

    static readonly grpc::Method<global::PassKitGrpcSDK.Filters, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> __Method_listCouponCampaigns = new grpc::Method<global::PassKitGrpcSDK.Filters, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "listCouponCampaigns",
        __Marshaller_io_Filters,
        __Marshaller_single_use_coupons_CouponCampaign);

    static readonly grpc::Method<global::PassKitGrpcSDK.AnalyticsRequest, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaignAnalyticsResponse> __Method_getAnalytics = new grpc::Method<global::PassKitGrpcSDK.AnalyticsRequest, global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaignAnalyticsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getAnalytics",
        __Marshaller_io_AnalyticsRequest,
        __Marshaller_single_use_coupons_CouponCampaignAnalyticsResponse);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer, global::PassKitGrpcSDK.Id> __Method_createCouponOffer = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer, global::PassKitGrpcSDK.Id>(
        grpc::MethodType.Unary,
        __ServiceName,
        "createCouponOffer",
        __Marshaller_single_use_coupons_CouponOffer,
        __Marshaller_io_Id);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer, global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> __Method_updateCouponOffer = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer, global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer>(
        grpc::MethodType.Unary,
        __ServiceName,
        "updateCouponOffer",
        __Marshaller_single_use_coupons_CouponOffer,
        __Marshaller_single_use_coupons_CouponOffer);

    static readonly grpc::Method<global::PassKitGrpcSDK.Id, global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> __Method_getCouponOffer = new grpc::Method<global::PassKitGrpcSDK.Id, global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getCouponOffer",
        __Marshaller_io_Id,
        __Marshaller_single_use_coupons_CouponOffer);

    static readonly grpc::Method<global::PassKitGrpcSDK.Id, global::Google.Protobuf.WellKnownTypes.Empty> __Method_deleteCouponOffer = new grpc::Method<global::PassKitGrpcSDK.Id, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "deleteCouponOffer",
        __Marshaller_io_Id,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequestDeprecated, global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> __Method_listCouponOffersDeprecated = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequestDeprecated, global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "listCouponOffersDeprecated",
        __Marshaller_single_use_coupons_CouponOffersListRequestDeprecated,
        __Marshaller_single_use_coupons_CouponOffer);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequest, global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> __Method_listCouponOffers = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequest, global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "listCouponOffers",
        __Marshaller_single_use_coupons_CouponOffersListRequest,
        __Marshaller_single_use_coupons_CouponOffer);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id> __Method_createCoupon = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id>(
        grpc::MethodType.Unary,
        __ServiceName,
        "createCoupon",
        __Marshaller_single_use_coupons_Coupon,
        __Marshaller_io_Id);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id> __Method_updateCoupon = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id>(
        grpc::MethodType.Unary,
        __ServiceName,
        "updateCoupon",
        __Marshaller_single_use_coupons_Coupon,
        __Marshaller_io_Id);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id> __Method_streamCouponUpdates = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "streamCouponUpdates",
        __Marshaller_single_use_coupons_Coupon,
        __Marshaller_io_Id);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id> __Method_redeemCoupon = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id>(
        grpc::MethodType.Unary,
        __ServiceName,
        "redeemCoupon",
        __Marshaller_single_use_coupons_Coupon,
        __Marshaller_io_Id);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponNewExternalIdRequest, global::PassKitGrpcSDK.Id> __Method_updateCouponExternalId = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CouponNewExternalIdRequest, global::PassKitGrpcSDK.Id>(
        grpc::MethodType.Unary,
        __ServiceName,
        "updateCouponExternalId",
        __Marshaller_single_use_coupons_CouponNewExternalIdRequest,
        __Marshaller_io_Id);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id> __Method_streamCouponRedemptions = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "streamCouponRedemptions",
        __Marshaller_single_use_coupons_Coupon,
        __Marshaller_io_Id);

    static readonly grpc::Method<global::PassKitGrpcSDK.Id, global::PassKitGrpcSDK.SingleUseCoupons.Coupon> __Method_getCouponById = new grpc::Method<global::PassKitGrpcSDK.Id, global::PassKitGrpcSDK.SingleUseCoupons.Coupon>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getCouponById",
        __Marshaller_io_Id,
        __Marshaller_single_use_coupons_Coupon);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.ExternalIdRequest, global::PassKitGrpcSDK.SingleUseCoupons.Coupon> __Method_getCouponByExternalId = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.ExternalIdRequest, global::PassKitGrpcSDK.SingleUseCoupons.Coupon>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getCouponByExternalId",
        __Marshaller_single_use_coupons_ExternalIdRequest,
        __Marshaller_single_use_coupons_Coupon);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::Google.Protobuf.WellKnownTypes.Empty> __Method_voidCoupon = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "voidCoupon",
        __Marshaller_single_use_coupons_Coupon,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated, global::PassKitGrpcSDK.SingleUseCoupons.Coupon> __Method_listCouponsByCouponCampaignDeprecated = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated, global::PassKitGrpcSDK.SingleUseCoupons.Coupon>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "listCouponsByCouponCampaignDeprecated",
        __Marshaller_single_use_coupons_ListRequestDeprecated,
        __Marshaller_single_use_coupons_Coupon);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.ListRequest, global::PassKitGrpcSDK.SingleUseCoupons.Coupon> __Method_listCouponsByCouponCampaign = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.ListRequest, global::PassKitGrpcSDK.SingleUseCoupons.Coupon>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "listCouponsByCouponCampaign",
        __Marshaller_single_use_coupons_ListRequest,
        __Marshaller_single_use_coupons_Coupon);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated, global::PassKitGrpcSDK.Count> __Method_countCouponsByCouponCampaignDeprecated = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated, global::PassKitGrpcSDK.Count>(
        grpc::MethodType.Unary,
        __ServiceName,
        "countCouponsByCouponCampaignDeprecated",
        __Marshaller_single_use_coupons_ListRequestDeprecated,
        __Marshaller_io_Count);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.ListRequest, global::PassKitGrpcSDK.Count> __Method_countCouponsByCouponCampaign = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.ListRequest, global::PassKitGrpcSDK.Count>(
        grpc::MethodType.Unary,
        __ServiceName,
        "countCouponsByCouponCampaign",
        __Marshaller_single_use_coupons_ListRequest,
        __Marshaller_io_Count);

    static readonly grpc::Method<global::PassKitGrpcSDK.PersonRequest, global::PassKitGrpcSDK.Id> __Method_patchPerson = new grpc::Method<global::PassKitGrpcSDK.PersonRequest, global::PassKitGrpcSDK.Id>(
        grpc::MethodType.Unary,
        __ServiceName,
        "patchPerson",
        __Marshaller_io_PersonRequest,
        __Marshaller_io_Id);

    static readonly grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CampaignCopyRequest, global::PassKitGrpcSDK.Id> __Method_copyCouponCampaign = new grpc::Method<global::PassKitGrpcSDK.SingleUseCoupons.CampaignCopyRequest, global::PassKitGrpcSDK.Id>(
        grpc::MethodType.Unary,
        __ServiceName,
        "copyCouponCampaign",
        __Marshaller_single_use_coupons_CampaignCopyRequest,
        __Marshaller_io_Id);

    static readonly grpc::Method<global::PassKitGrpcSDK.Id, global::PassKitGrpcSDK.Strings> __Method_getMetaKeysForCampaign = new grpc::Method<global::PassKitGrpcSDK.Id, global::PassKitGrpcSDK.Strings>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getMetaKeysForCampaign",
        __Marshaller_io_Id,
        __Marshaller_io_Strings);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PassKitGrpcSDK.SingleUseCoupons.ARpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for SingleUseCoupons</summary>
    public partial class SingleUseCouponsClient : grpc::ClientBase<SingleUseCouponsClient>
    {
      /// <summary>Creates a new client for SingleUseCoupons</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SingleUseCouponsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SingleUseCoupons that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SingleUseCouponsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SingleUseCouponsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SingleUseCouponsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::PassKitGrpcSDK.Id createCouponCampaign(global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return createCouponCampaign(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.Id createCouponCampaign(global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_createCouponCampaign, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> createCouponCampaignAsync(global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return createCouponCampaignAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> createCouponCampaignAsync(global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_createCouponCampaign, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign updateCouponCampaign(global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return updateCouponCampaign(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign updateCouponCampaign(global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_updateCouponCampaign, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> updateCouponCampaignAsync(global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return updateCouponCampaignAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> updateCouponCampaignAsync(global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_updateCouponCampaign, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign getCouponCampaign(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getCouponCampaign(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign getCouponCampaign(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getCouponCampaign, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> getCouponCampaignAsync(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getCouponCampaignAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> getCouponCampaignAsync(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getCouponCampaign, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty deleteCouponCampaign(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return deleteCouponCampaign(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty deleteCouponCampaign(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_deleteCouponCampaign, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> deleteCouponCampaignAsync(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return deleteCouponCampaignAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> deleteCouponCampaignAsync(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_deleteCouponCampaign, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> listCouponCampaignsDeprecated(global::PassKitGrpcSDK.Pagination request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return listCouponCampaignsDeprecated(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> listCouponCampaignsDeprecated(global::PassKitGrpcSDK.Pagination request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_listCouponCampaignsDeprecated, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> listCouponCampaigns(global::PassKitGrpcSDK.Filters request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return listCouponCampaigns(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaign> listCouponCampaigns(global::PassKitGrpcSDK.Filters request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_listCouponCampaigns, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaignAnalyticsResponse getAnalytics(global::PassKitGrpcSDK.AnalyticsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getAnalytics(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaignAnalyticsResponse getAnalytics(global::PassKitGrpcSDK.AnalyticsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getAnalytics, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaignAnalyticsResponse> getAnalyticsAsync(global::PassKitGrpcSDK.AnalyticsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getAnalyticsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponCampaignAnalyticsResponse> getAnalyticsAsync(global::PassKitGrpcSDK.AnalyticsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getAnalytics, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.Id createCouponOffer(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return createCouponOffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.Id createCouponOffer(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_createCouponOffer, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> createCouponOfferAsync(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return createCouponOfferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> createCouponOfferAsync(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_createCouponOffer, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer updateCouponOffer(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return updateCouponOffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer updateCouponOffer(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_updateCouponOffer, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> updateCouponOfferAsync(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return updateCouponOfferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> updateCouponOfferAsync(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_updateCouponOffer, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer getCouponOffer(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getCouponOffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer getCouponOffer(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getCouponOffer, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> getCouponOfferAsync(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getCouponOfferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> getCouponOfferAsync(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getCouponOffer, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty deleteCouponOffer(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return deleteCouponOffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty deleteCouponOffer(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_deleteCouponOffer, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> deleteCouponOfferAsync(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return deleteCouponOfferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> deleteCouponOfferAsync(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_deleteCouponOffer, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> listCouponOffersDeprecated(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequestDeprecated request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return listCouponOffersDeprecated(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> listCouponOffersDeprecated(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequestDeprecated request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_listCouponOffersDeprecated, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> listCouponOffers(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return listCouponOffers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.CouponOffer> listCouponOffers(global::PassKitGrpcSDK.SingleUseCoupons.CouponOffersListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_listCouponOffers, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.Id createCoupon(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return createCoupon(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.Id createCoupon(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_createCoupon, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> createCouponAsync(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return createCouponAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> createCouponAsync(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_createCoupon, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.Id updateCoupon(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return updateCoupon(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.Id updateCoupon(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_updateCoupon, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> updateCouponAsync(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return updateCouponAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> updateCouponAsync(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_updateCoupon, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id> streamCouponUpdates(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return streamCouponUpdates(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id> streamCouponUpdates(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_streamCouponUpdates, null, options);
      }
      public virtual global::PassKitGrpcSDK.Id redeemCoupon(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return redeemCoupon(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.Id redeemCoupon(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_redeemCoupon, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> redeemCouponAsync(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return redeemCouponAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> redeemCouponAsync(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_redeemCoupon, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.Id updateCouponExternalId(global::PassKitGrpcSDK.SingleUseCoupons.CouponNewExternalIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return updateCouponExternalId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.Id updateCouponExternalId(global::PassKitGrpcSDK.SingleUseCoupons.CouponNewExternalIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_updateCouponExternalId, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> updateCouponExternalIdAsync(global::PassKitGrpcSDK.SingleUseCoupons.CouponNewExternalIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return updateCouponExternalIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> updateCouponExternalIdAsync(global::PassKitGrpcSDK.SingleUseCoupons.CouponNewExternalIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_updateCouponExternalId, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id> streamCouponRedemptions(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return streamCouponRedemptions(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon, global::PassKitGrpcSDK.Id> streamCouponRedemptions(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_streamCouponRedemptions, null, options);
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.Coupon getCouponById(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getCouponById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.Coupon getCouponById(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getCouponById, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon> getCouponByIdAsync(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getCouponByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon> getCouponByIdAsync(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getCouponById, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.Coupon getCouponByExternalId(global::PassKitGrpcSDK.SingleUseCoupons.ExternalIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getCouponByExternalId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.SingleUseCoupons.Coupon getCouponByExternalId(global::PassKitGrpcSDK.SingleUseCoupons.ExternalIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getCouponByExternalId, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon> getCouponByExternalIdAsync(global::PassKitGrpcSDK.SingleUseCoupons.ExternalIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getCouponByExternalIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon> getCouponByExternalIdAsync(global::PassKitGrpcSDK.SingleUseCoupons.ExternalIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getCouponByExternalId, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty voidCoupon(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return voidCoupon(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty voidCoupon(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_voidCoupon, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> voidCouponAsync(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return voidCouponAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> voidCouponAsync(global::PassKitGrpcSDK.SingleUseCoupons.Coupon request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_voidCoupon, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon> listCouponsByCouponCampaignDeprecated(global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return listCouponsByCouponCampaignDeprecated(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon> listCouponsByCouponCampaignDeprecated(global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_listCouponsByCouponCampaignDeprecated, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon> listCouponsByCouponCampaign(global::PassKitGrpcSDK.SingleUseCoupons.ListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return listCouponsByCouponCampaign(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PassKitGrpcSDK.SingleUseCoupons.Coupon> listCouponsByCouponCampaign(global::PassKitGrpcSDK.SingleUseCoupons.ListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_listCouponsByCouponCampaign, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.Count countCouponsByCouponCampaignDeprecated(global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return countCouponsByCouponCampaignDeprecated(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.Count countCouponsByCouponCampaignDeprecated(global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_countCouponsByCouponCampaignDeprecated, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Count> countCouponsByCouponCampaignDeprecatedAsync(global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return countCouponsByCouponCampaignDeprecatedAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Count> countCouponsByCouponCampaignDeprecatedAsync(global::PassKitGrpcSDK.SingleUseCoupons.ListRequestDeprecated request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_countCouponsByCouponCampaignDeprecated, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.Count countCouponsByCouponCampaign(global::PassKitGrpcSDK.SingleUseCoupons.ListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return countCouponsByCouponCampaign(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.Count countCouponsByCouponCampaign(global::PassKitGrpcSDK.SingleUseCoupons.ListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_countCouponsByCouponCampaign, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Count> countCouponsByCouponCampaignAsync(global::PassKitGrpcSDK.SingleUseCoupons.ListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return countCouponsByCouponCampaignAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Count> countCouponsByCouponCampaignAsync(global::PassKitGrpcSDK.SingleUseCoupons.ListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_countCouponsByCouponCampaign, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.Id patchPerson(global::PassKitGrpcSDK.PersonRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return patchPerson(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.Id patchPerson(global::PassKitGrpcSDK.PersonRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_patchPerson, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> patchPersonAsync(global::PassKitGrpcSDK.PersonRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return patchPersonAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> patchPersonAsync(global::PassKitGrpcSDK.PersonRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_patchPerson, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.Id copyCouponCampaign(global::PassKitGrpcSDK.SingleUseCoupons.CampaignCopyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return copyCouponCampaign(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.Id copyCouponCampaign(global::PassKitGrpcSDK.SingleUseCoupons.CampaignCopyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_copyCouponCampaign, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> copyCouponCampaignAsync(global::PassKitGrpcSDK.SingleUseCoupons.CampaignCopyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return copyCouponCampaignAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Id> copyCouponCampaignAsync(global::PassKitGrpcSDK.SingleUseCoupons.CampaignCopyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_copyCouponCampaign, null, options, request);
      }
      public virtual global::PassKitGrpcSDK.Strings getMetaKeysForCampaign(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getMetaKeysForCampaign(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PassKitGrpcSDK.Strings getMetaKeysForCampaign(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getMetaKeysForCampaign, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Strings> getMetaKeysForCampaignAsync(global::PassKitGrpcSDK.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getMetaKeysForCampaignAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PassKitGrpcSDK.Strings> getMetaKeysForCampaignAsync(global::PassKitGrpcSDK.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getMetaKeysForCampaign, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SingleUseCouponsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SingleUseCouponsClient(configuration);
      }
    }

  }
}
#endregion
