// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protoc-gen-swagger/options/annotations.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grpc.Gateway.ProtocGenSwagger.Options {

  /// <summary>Holder for reflection information generated from protoc-gen-swagger/options/annotations.proto</summary>
  public static partial class AnnotationsReflection {

    #region Descriptor
    /// <summary>File descriptor for protoc-gen-swagger/options/annotations.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnnotationsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixwcm90b2MtZ2VuLXN3YWdnZXIvb3B0aW9ucy9hbm5vdGF0aW9ucy5wcm90",
            "bxInZ3JwYy5nYXRld2F5LnByb3RvY19nZW5fc3dhZ2dlci5vcHRpb25zGipw",
            "cm90b2MtZ2VuLXN3YWdnZXIvb3B0aW9ucy9vcGVuYXBpdjIucHJvdG8aIGdv",
            "b2dsZS9wcm90b2J1Zi9kZXNjcmlwdG9yLnByb3RvOmoKEW9wZW5hcGl2Ml9z",
            "d2FnZ2VyEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGJIIIAEoCzIw",
            "LmdycGMuZ2F0ZXdheS5wcm90b2NfZ2VuX3N3YWdnZXIub3B0aW9ucy5Td2Fn",
            "Z2VyOnAKE29wZW5hcGl2Ml9vcGVyYXRpb24SHi5nb29nbGUucHJvdG9idWYu",
            "TWV0aG9kT3B0aW9ucxiSCCABKAsyMi5ncnBjLmdhdGV3YXkucHJvdG9jX2dl",
            "bl9zd2FnZ2VyLm9wdGlvbnMuT3BlcmF0aW9uOmsKEG9wZW5hcGl2Ml9zY2hl",
            "bWESHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYkgggASgLMi8u",
            "Z3JwYy5nYXRld2F5LnByb3RvY19nZW5fc3dhZ2dlci5vcHRpb25zLlNjaGVt",
            "YTplCg1vcGVuYXBpdjJfdGFnEh8uZ29vZ2xlLnByb3RvYnVmLlNlcnZpY2VP",
            "cHRpb25zGJIIIAEoCzIsLmdycGMuZ2F0ZXdheS5wcm90b2NfZ2VuX3N3YWdn",
            "ZXIub3B0aW9ucy5UYWc6bAoPb3BlbmFwaXYyX2ZpZWxkEh0uZ29vZ2xlLnBy",
            "b3RvYnVmLkZpZWxkT3B0aW9ucxiSCCABKAsyMy5ncnBjLmdhdGV3YXkucHJv",
            "dG9jX2dlbl9zd2FnZ2VyLm9wdGlvbnMuSlNPTlNjaGVtYUJDWkFnaXRodWIu",
            "Y29tL2dycGMtZWNvc3lzdGVtL2dycGMtZ2F0ZXdheS9wcm90b2MtZ2VuLXN3",
            "YWdnZXIvb3B0aW9uc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Grpc.Gateway.ProtocGenSwagger.Options.Openapiv2Reflection.Descriptor, pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
