// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: io/core/a_rpc_messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PassKit.Grpc {

  /// <summary>Holder for reflection information generated from io/core/a_rpc_messages.proto</summary>
  public static partial class ARpcMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for io/core/a_rpc_messages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ARpcMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chxpby9jb3JlL2FfcnBjX21lc3NhZ2VzLnByb3RvEgJpbxocZ29vZ2xlL2Fw",
            "aS9hbm5vdGF0aW9ucy5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnBy",
            "b3RvGi5wcm90b2MtZ2VuLW9wZW5hcGl2Mi9vcHRpb25zL2Fubm90YXRpb25z",
            "LnByb3RvGh5pby9jb21tb24vY29tbW9uX29iamVjdHMucHJvdG8aF2lvL2Nv",
            "bW1vbi9tZXNzYWdlLnByb3RvMtgGCghNZXNzYWdlcxJvCgpnZXRNZXNzYWdl",
            "EgYuaW8uSWQaCy5pby5NZXNzYWdlIkySQTQSC0dldCBtZXNzYWdlGiVHZXRz",
            "IGFuIHNpbmdsZSBtZXNzYWdlIGJ5IG1lc3NhZ2UgaWQugtPkkwIPEg0vbWVz",
            "c2FnZS97aWR9EpYBCg1jcmVhdGVNZXNzYWdlEgsuaW8uTWVzc2FnZRoGLmlv",
            "LklkInCSQVoSDkNyZWF0ZSBNZXNzYWdlGhZDcmVhdGVzIGEgbmV3IG1lc3Nh",
            "Z2UuSjAKAzQwMBIpCidUaGVyZSBpcyBhIHByb2JsZW0gd2l0aCB0aGUgaW5w",
            "dXQgZGF0YS6C0+STAg0iCC9tZXNzYWdlOgEqEqQBCg11cGRhdGVNZXNzYWdl",
            "EgsuaW8uTWVzc2FnZRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSJukkFTEg5V",
            "cGRhdGUgTWVzc2FnZRoPVXBkYXRlIG1lc3NhZ2UuSjAKAzQwMBIpCidUaGVy",
            "ZSBpcyBhIHByb2JsZW0gd2l0aCB0aGUgaW5wdXQgZGF0YS6C0+STAhIaDS9t",
            "ZXNzYWdlL3tpZH06ASoStAEKDWRlbGV0ZU1lc3NhZ2USBi5pby5JZBoWLmdv",
            "b2dsZS5wcm90b2J1Zi5FbXB0eSKCAZJBahIORGVsZXRlIE1lc3NhZ2UaMkRl",
            "bGV0aW5nIGEgbWVzc2FnZSB3aWxsIHJlbW92ZSBpdCBmcm9tIGFsbCBwYXNz",
            "ZXMuSiQKAzQwNBIdChtNZXNzYWdlIGNvdWxkIG5vdCBiZSBmb3VuZC6C0+ST",
            "Ag8qDS9tZXNzYWdlL3tpZH0S4wEKC3NlbmRNZXNzYWdlEhYuaW8uU2VuZE1l",
            "c3NhZ2VSZXF1ZXN0GhcuaW8uU2VuZE1lc3NhZ2VSZXNwb25zZSKiAZJBhgES",
            "DFNlbmQgTWVzc2FnZRpEU2VuZHMgYSBtZXNzYWdlIHRvIGFuIGFycmF5IG9m",
            "IHBhc3NJZHMsIG9yIHRvIGV2ZXJ5IHBhc3MgaW4gYSBjbGFzcy5KMAoDNDAw",
            "EikKJ1RoZXJlIGlzIGEgcHJvYmxlbSB3aXRoIHRoZSBpbnB1dCBkYXRhLoLT",
            "5JMCEiINL21lc3NhZ2Uvc2VuZDoBKkJHChBjb20ucGFzc2tpdC5ncnBjWiRz",
            "dGFzaC5wYXNza2l0LmNvbS9pby9tb2RlbC9zZGsvZ28vaW+qAgxQYXNzS2l0",
            "LkdycGNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::PassKit.Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, global::PassKit.Grpc.CommonObjectsReflection.Descriptor, global::PassKit.Grpc.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
