// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: io/event_tickets/production.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PassKit.Grpc.EventTickets {

  /// <summary>Holder for reflection information generated from io/event_tickets/production.proto</summary>
  public static partial class ProductionReflection {

    #region Descriptor
    /// <summary>File descriptor for io/event_tickets/production.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProductionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFpby9ldmVudF90aWNrZXRzL3Byb2R1Y3Rpb24ucHJvdG8SDWV2ZW50X3Rp",
            "Y2tldHMaH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8aHGlvL2Nv",
            "bW1vbi9kaXN0cmlidXRpb24ucHJvdG8aHGlvL2NvbW1vbi9sb2NhbGl6YXRp",
            "b24ucHJvdG8aF2lvL2NvbW1vbi9wcm9qZWN0LnByb3RvGhlpby9jb21tb24v",
            "cmVwb3J0aW5nLnByb3RvGh5pby9jb21tb24vY29tbW9uX29iamVjdHMucHJv",
            "dG8aLnByb3RvYy1nZW4tb3BlbmFwaXYyL29wdGlvbnMvYW5ub3RhdGlvbnMu",
            "cHJvdG8i1wUKClByb2R1Y3Rpb24SEQoCaWQYASABKAlCBZJBAkABEgsKA3Vp",
            "ZBgCIAEoCRIMCgRuYW1lGAMgASgJEioKDWxvY2FsaXplZE5hbWUYBCABKAsy",
            "Ey5pby5Mb2NhbGl6ZWRTdHJpbmcSEQoJZmluZVByaW50GAUgASgJEi8KEmxv",
            "Y2FsaXplZEZpbmVQcmludBgGIAEoCzITLmlvLkxvY2FsaXplZFN0cmluZxI3",
            "CiNhdXRvSW52YWxpZGF0ZVRpY2tldHNVcG9uUmVkZW1wdGlvbhgHIAEoDjIK",
            "LmlvLlRvZ2dsZRI1CiFhdXRvSW52YWxpZGF0ZVRpY2tldHNVcG9uRXZlbnRF",
            "bmQYCCABKA4yCi5pby5Ub2dnbGUSMwofYXV0b0ludmFsaWRhdGVUaWNrZXRz",
            "VXBvbkV4cGlyeRgJIAEoDjIKLmlvLlRvZ2dsZRIhCgZzdGF0dXMYCiADKA4y",
            "ES5pby5Qcm9qZWN0U3RhdHVzEhoKEnBhc3NUeXBlSWRlbnRpZmllchgLIAEo",
            "CRI2ChRkaXN0cmlidXRpb25TZXR0aW5ncxgMIAEoCzIYLmlvLkRpc3RyaWJ1",
            "dGlvblNldHRpbmdzEjIKB2NyZWF0ZWQYDSABKAsyGi5nb29nbGUucHJvdG9i",
            "dWYuVGltZXN0YW1wQgWSQQJAARIyCgd1cGRhdGVkGA4gASgLMhouZ29vZ2xl",
            "LnByb3RvYnVmLlRpbWVzdGFtcEIFkkECQAE6pgGSQaIBCp8BKgpQcm9kdWN0",
            "aW9uMokBUHJvZHVjdGlvbiBjb250YWlucyBkYXRhIHRoYXQgaXMgc2hhcmVk",
            "IGJ5IGV2ZW50czogY29tbW9uIGV2ZW50IHByb3BlcnRpZXMgLyBzZXR0aW5n",
            "cywgZGlzdHJpYnV0aW9uIHNldHRpbmdzIGFuZCBBcHBsZSBQYXNzIFR5cGUg",
            "ZGV0YWlscy7SAQRuYW1lIo4CChtQcm9kdWN0aW9uQW5hbHl0aWNzUmVzcG9u",
            "c2USGgoGcGVyaW9kGAEgASgOMgouaW8uUGVyaW9kEhAKCHJlZGVlbWVkGAIg",
            "ASgNEiQKB2RldmljZXMYAyABKAsyEy5pby5EZXZpY2VCcmVha2Rvd24SSAoH",
            "c291cmNlcxgEIAMoCzI3LmV2ZW50X3RpY2tldHMuUHJvZHVjdGlvbkFuYWx5",
            "dGljc1Jlc3BvbnNlLlNvdXJjZXNFbnRyeRIhCgRkYXRhGAUgAygLMhMuaW8u",
            "Q2hhcnREYXRhUG9pbnRzGi4KDFNvdXJjZXNFbnRyeRILCgNrZXkYASABKAkS",
            "DQoFdmFsdWUYAiABKA06AjgBIn0KFVByb2R1Y3Rpb25Db3B5UmVxdWVzdBIK",
            "CgJpZBgBIAEoCRILCgN1aWQYAiABKAkSDAoEbmFtZRgDIAEoCRIhCgZzdGF0",
            "dXMYBCADKA4yES5pby5Qcm9qZWN0U3RhdHVzEhoKEnBhc3NUeXBlSWRlbnRp",
            "ZmllchgFIAEoCSL2AQofUHJvZHVjdGlvbkxpbWl0ZWRGaWVsZHNSZXNwb25z",
            "ZRIKCgJpZBgBIAEoCRILCgN1aWQYAiABKAkSDAoEbmFtZRgDIAEoCTqrAZJB",
            "pwEKpAEqFlByb2R1Y3Rpb24gKExpZ2h0IHZlcikyiQFQcm9kdWN0aW9uIGNv",
            "bnRhaW5zIGRhdGEgdGhhdCBpcyBzaGFyZWQgYnkgZXZlbnRzOiBjb21tb24g",
            "ZXZlbnQgcHJvcGVydGllcyAvIHNldHRpbmdzLCBkaXN0cmlidXRpb24gc2V0",
            "dGluZ3MgYW5kIEFwcGxlIFBhc3MgVHlwZSBkZXRhaWxzLkJvCh1jb20ucGFz",
            "c2tpdC5ncnBjLkV2ZW50VGlja2V0c1oyc3Rhc2gucGFzc2tpdC5jb20vaW8v",
            "bW9kZWwvc2RrL2dvL2lvL2V2ZW50X3RpY2tldHOqAhlQYXNzS2l0LkdycGMu",
            "RXZlbnRUaWNrZXRzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::PassKit.Grpc.DistributionReflection.Descriptor, global::PassKit.Grpc.LocalizationReflection.Descriptor, global::PassKit.Grpc.ProjectReflection.Descriptor, global::PassKit.Grpc.ReportingReflection.Descriptor, global::PassKit.Grpc.CommonObjectsReflection.Descriptor, global::PassKit.Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PassKit.Grpc.EventTickets.Production), global::PassKit.Grpc.EventTickets.Production.Parser, new[]{ "Id", "Uid", "Name", "LocalizedName", "FinePrint", "LocalizedFinePrint", "AutoInvalidateTicketsUponRedemption", "AutoInvalidateTicketsUponEventEnd", "AutoInvalidateTicketsUponExpiry", "Status", "PassTypeIdentifier", "DistributionSettings", "Created", "Updated" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PassKit.Grpc.EventTickets.ProductionAnalyticsResponse), global::PassKit.Grpc.EventTickets.ProductionAnalyticsResponse.Parser, new[]{ "Period", "Redeemed", "Devices", "Sources", "Data" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::PassKit.Grpc.EventTickets.ProductionCopyRequest), global::PassKit.Grpc.EventTickets.ProductionCopyRequest.Parser, new[]{ "Id", "Uid", "Name", "Status", "PassTypeIdentifier" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PassKit.Grpc.EventTickets.ProductionLimitedFieldsResponse), global::PassKit.Grpc.EventTickets.ProductionLimitedFieldsResponse.Parser, new[]{ "Id", "Uid", "Name" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Production : pb::IMessage<Production>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Production> _parser = new pb::MessageParser<Production>(() => new Production());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Production> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PassKit.Grpc.EventTickets.ProductionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Production() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Production(Production other) : this() {
      id_ = other.id_;
      uid_ = other.uid_;
      name_ = other.name_;
      localizedName_ = other.localizedName_ != null ? other.localizedName_.Clone() : null;
      finePrint_ = other.finePrint_;
      localizedFinePrint_ = other.localizedFinePrint_ != null ? other.localizedFinePrint_.Clone() : null;
      autoInvalidateTicketsUponRedemption_ = other.autoInvalidateTicketsUponRedemption_;
      autoInvalidateTicketsUponEventEnd_ = other.autoInvalidateTicketsUponEventEnd_;
      autoInvalidateTicketsUponExpiry_ = other.autoInvalidateTicketsUponExpiry_;
      status_ = other.status_.Clone();
      passTypeIdentifier_ = other.passTypeIdentifier_;
      distributionSettings_ = other.distributionSettings_ != null ? other.distributionSettings_.Clone() : null;
      created_ = other.created_ != null ? other.created_.Clone() : null;
      updated_ = other.updated_ != null ? other.updated_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Production Clone() {
      return new Production(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    /// PassKit generated production id (22 characters).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 2;
    private string uid_ = "";
    /// <summary>
    /// User generated production id; unique within the account.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    /// <summary>
    /// Name of the production (i.e. Les Miserables, The Lion King, Avengers, etc).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "localizedName" field.</summary>
    public const int LocalizedNameFieldNumber = 4;
    private global::PassKit.Grpc.LocalizedString localizedName_;
    /// <summary>
    /// Localized name of the production.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PassKit.Grpc.LocalizedString LocalizedName {
      get { return localizedName_; }
      set {
        localizedName_ = value;
      }
    }

    /// <summary>Field number for the "finePrint" field.</summary>
    public const int FinePrintFieldNumber = 5;
    private string finePrint_ = "";
    /// <summary>
    /// Fine print: terms &amp; conditions for the production.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FinePrint {
      get { return finePrint_; }
      set {
        finePrint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "localizedFinePrint" field.</summary>
    public const int LocalizedFinePrintFieldNumber = 6;
    private global::PassKit.Grpc.LocalizedString localizedFinePrint_;
    /// <summary>
    /// Localized fine print of the production.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PassKit.Grpc.LocalizedString LocalizedFinePrint {
      get { return localizedFinePrint_; }
      set {
        localizedFinePrint_ = value;
      }
    }

    /// <summary>Field number for the "autoInvalidateTicketsUponRedemption" field.</summary>
    public const int AutoInvalidateTicketsUponRedemptionFieldNumber = 7;
    private global::PassKit.Grpc.Toggle autoInvalidateTicketsUponRedemption_ = global::PassKit.Grpc.Toggle.DoNotUse;
    /// <summary>
    /// If set will automatically delete the ticket and invalidate the pass in our system upon ticket redemption. If not set, the tickets will expire 90 days after issue. If the ticket is not auto invalidated it can be used for further engagement.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PassKit.Grpc.Toggle AutoInvalidateTicketsUponRedemption {
      get { return autoInvalidateTicketsUponRedemption_; }
      set {
        autoInvalidateTicketsUponRedemption_ = value;
      }
    }

    /// <summary>Field number for the "autoInvalidateTicketsUponEventEnd" field.</summary>
    public const int AutoInvalidateTicketsUponEventEndFieldNumber = 8;
    private global::PassKit.Grpc.Toggle autoInvalidateTicketsUponEventEnd_ = global::PassKit.Grpc.Toggle.DoNotUse;
    /// <summary>
    /// If set will automatically delete the ticket and invalidate the pass in our system 1 day after the event end date (if set). If event date is not set, it will expire 1 day after event start date. If not set, the tickets will expire 90 days after issue. If the ticket is not auto invalidated it can be used for further engagement.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PassKit.Grpc.Toggle AutoInvalidateTicketsUponEventEnd {
      get { return autoInvalidateTicketsUponEventEnd_; }
      set {
        autoInvalidateTicketsUponEventEnd_ = value;
      }
    }

    /// <summary>Field number for the "autoInvalidateTicketsUponExpiry" field.</summary>
    public const int AutoInvalidateTicketsUponExpiryFieldNumber = 9;
    private global::PassKit.Grpc.Toggle autoInvalidateTicketsUponExpiry_ = global::PassKit.Grpc.Toggle.DoNotUse;
    /// <summary>
    /// If set will automatically delete the ticket and invalidate the pass in our system upon ticket expiry. If not set, the tickets will expire 90 days after issue. If the ticket is not auto invalidated it can be used for further engagement.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PassKit.Grpc.Toggle AutoInvalidateTicketsUponExpiry {
      get { return autoInvalidateTicketsUponExpiry_; }
      set {
        autoInvalidateTicketsUponExpiry_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 10;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.ProjectStatus> _repeated_status_codec
        = pb::FieldCodec.ForEnum(82, x => (int) x, x => (global::PassKit.Grpc.ProjectStatus) x);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.ProjectStatus> status_ = new pbc::RepeatedField<global::PassKit.Grpc.ProjectStatus>();
    /// <summary>
    /// The events status (bitmask of ProjectStatus). Defaults to io.ProjectStatus.PROJECT_ACTIVE_FOR_OBJECT_CREATION + io.ProjectStatus.PROJECT_DRAFT.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.ProjectStatus> Status {
      get { return status_; }
    }

    /// <summary>Field number for the "passTypeIdentifier" field.</summary>
    public const int PassTypeIdentifierFieldNumber = 11;
    private string passTypeIdentifier_ = "";
    /// <summary>
    /// Leave empty for draft production. Needs to be set for productions where status contains PROJECT_PUBLISHED.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PassTypeIdentifier {
      get { return passTypeIdentifier_; }
      set {
        passTypeIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "distributionSettings" field.</summary>
    public const int DistributionSettingsFieldNumber = 12;
    private global::PassKit.Grpc.DistributionSettings distributionSettings_;
    /// <summary>
    /// Contains the email &amp; sms distribution settings for the production.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PassKit.Grpc.DistributionSettings DistributionSettings {
      get { return distributionSettings_; }
      set {
        distributionSettings_ = value;
      }
    }

    /// <summary>Field number for the "created" field.</summary>
    public const int CreatedFieldNumber = 13;
    private global::Google.Protobuf.WellKnownTypes.Timestamp created_;
    /// <summary>
    /// The date the event was created. Not writable.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Created {
      get { return created_; }
      set {
        created_ = value;
      }
    }

    /// <summary>Field number for the "updated" field.</summary>
    public const int UpdatedFieldNumber = 14;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updated_;
    /// <summary>
    /// The date the event updated. Not writable.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Updated {
      get { return updated_; }
      set {
        updated_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Production);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Production other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Uid != other.Uid) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(LocalizedName, other.LocalizedName)) return false;
      if (FinePrint != other.FinePrint) return false;
      if (!object.Equals(LocalizedFinePrint, other.LocalizedFinePrint)) return false;
      if (AutoInvalidateTicketsUponRedemption != other.AutoInvalidateTicketsUponRedemption) return false;
      if (AutoInvalidateTicketsUponEventEnd != other.AutoInvalidateTicketsUponEventEnd) return false;
      if (AutoInvalidateTicketsUponExpiry != other.AutoInvalidateTicketsUponExpiry) return false;
      if(!status_.Equals(other.status_)) return false;
      if (PassTypeIdentifier != other.PassTypeIdentifier) return false;
      if (!object.Equals(DistributionSettings, other.DistributionSettings)) return false;
      if (!object.Equals(Created, other.Created)) return false;
      if (!object.Equals(Updated, other.Updated)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Uid.Length != 0) hash ^= Uid.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (localizedName_ != null) hash ^= LocalizedName.GetHashCode();
      if (FinePrint.Length != 0) hash ^= FinePrint.GetHashCode();
      if (localizedFinePrint_ != null) hash ^= LocalizedFinePrint.GetHashCode();
      if (AutoInvalidateTicketsUponRedemption != global::PassKit.Grpc.Toggle.DoNotUse) hash ^= AutoInvalidateTicketsUponRedemption.GetHashCode();
      if (AutoInvalidateTicketsUponEventEnd != global::PassKit.Grpc.Toggle.DoNotUse) hash ^= AutoInvalidateTicketsUponEventEnd.GetHashCode();
      if (AutoInvalidateTicketsUponExpiry != global::PassKit.Grpc.Toggle.DoNotUse) hash ^= AutoInvalidateTicketsUponExpiry.GetHashCode();
      hash ^= status_.GetHashCode();
      if (PassTypeIdentifier.Length != 0) hash ^= PassTypeIdentifier.GetHashCode();
      if (distributionSettings_ != null) hash ^= DistributionSettings.GetHashCode();
      if (created_ != null) hash ^= Created.GetHashCode();
      if (updated_ != null) hash ^= Updated.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Uid);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (localizedName_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LocalizedName);
      }
      if (FinePrint.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FinePrint);
      }
      if (localizedFinePrint_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(LocalizedFinePrint);
      }
      if (AutoInvalidateTicketsUponRedemption != global::PassKit.Grpc.Toggle.DoNotUse) {
        output.WriteRawTag(56);
        output.WriteEnum((int) AutoInvalidateTicketsUponRedemption);
      }
      if (AutoInvalidateTicketsUponEventEnd != global::PassKit.Grpc.Toggle.DoNotUse) {
        output.WriteRawTag(64);
        output.WriteEnum((int) AutoInvalidateTicketsUponEventEnd);
      }
      if (AutoInvalidateTicketsUponExpiry != global::PassKit.Grpc.Toggle.DoNotUse) {
        output.WriteRawTag(72);
        output.WriteEnum((int) AutoInvalidateTicketsUponExpiry);
      }
      status_.WriteTo(output, _repeated_status_codec);
      if (PassTypeIdentifier.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(PassTypeIdentifier);
      }
      if (distributionSettings_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(DistributionSettings);
      }
      if (created_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(Created);
      }
      if (updated_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(Updated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Uid);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (localizedName_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LocalizedName);
      }
      if (FinePrint.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FinePrint);
      }
      if (localizedFinePrint_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(LocalizedFinePrint);
      }
      if (AutoInvalidateTicketsUponRedemption != global::PassKit.Grpc.Toggle.DoNotUse) {
        output.WriteRawTag(56);
        output.WriteEnum((int) AutoInvalidateTicketsUponRedemption);
      }
      if (AutoInvalidateTicketsUponEventEnd != global::PassKit.Grpc.Toggle.DoNotUse) {
        output.WriteRawTag(64);
        output.WriteEnum((int) AutoInvalidateTicketsUponEventEnd);
      }
      if (AutoInvalidateTicketsUponExpiry != global::PassKit.Grpc.Toggle.DoNotUse) {
        output.WriteRawTag(72);
        output.WriteEnum((int) AutoInvalidateTicketsUponExpiry);
      }
      status_.WriteTo(ref output, _repeated_status_codec);
      if (PassTypeIdentifier.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(PassTypeIdentifier);
      }
      if (distributionSettings_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(DistributionSettings);
      }
      if (created_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(Created);
      }
      if (updated_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(Updated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (localizedName_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalizedName);
      }
      if (FinePrint.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FinePrint);
      }
      if (localizedFinePrint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalizedFinePrint);
      }
      if (AutoInvalidateTicketsUponRedemption != global::PassKit.Grpc.Toggle.DoNotUse) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AutoInvalidateTicketsUponRedemption);
      }
      if (AutoInvalidateTicketsUponEventEnd != global::PassKit.Grpc.Toggle.DoNotUse) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AutoInvalidateTicketsUponEventEnd);
      }
      if (AutoInvalidateTicketsUponExpiry != global::PassKit.Grpc.Toggle.DoNotUse) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AutoInvalidateTicketsUponExpiry);
      }
      size += status_.CalculateSize(_repeated_status_codec);
      if (PassTypeIdentifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PassTypeIdentifier);
      }
      if (distributionSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DistributionSettings);
      }
      if (created_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Created);
      }
      if (updated_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Updated);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Production other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Uid.Length != 0) {
        Uid = other.Uid;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.localizedName_ != null) {
        if (localizedName_ == null) {
          LocalizedName = new global::PassKit.Grpc.LocalizedString();
        }
        LocalizedName.MergeFrom(other.LocalizedName);
      }
      if (other.FinePrint.Length != 0) {
        FinePrint = other.FinePrint;
      }
      if (other.localizedFinePrint_ != null) {
        if (localizedFinePrint_ == null) {
          LocalizedFinePrint = new global::PassKit.Grpc.LocalizedString();
        }
        LocalizedFinePrint.MergeFrom(other.LocalizedFinePrint);
      }
      if (other.AutoInvalidateTicketsUponRedemption != global::PassKit.Grpc.Toggle.DoNotUse) {
        AutoInvalidateTicketsUponRedemption = other.AutoInvalidateTicketsUponRedemption;
      }
      if (other.AutoInvalidateTicketsUponEventEnd != global::PassKit.Grpc.Toggle.DoNotUse) {
        AutoInvalidateTicketsUponEventEnd = other.AutoInvalidateTicketsUponEventEnd;
      }
      if (other.AutoInvalidateTicketsUponExpiry != global::PassKit.Grpc.Toggle.DoNotUse) {
        AutoInvalidateTicketsUponExpiry = other.AutoInvalidateTicketsUponExpiry;
      }
      status_.Add(other.status_);
      if (other.PassTypeIdentifier.Length != 0) {
        PassTypeIdentifier = other.PassTypeIdentifier;
      }
      if (other.distributionSettings_ != null) {
        if (distributionSettings_ == null) {
          DistributionSettings = new global::PassKit.Grpc.DistributionSettings();
        }
        DistributionSettings.MergeFrom(other.DistributionSettings);
      }
      if (other.created_ != null) {
        if (created_ == null) {
          Created = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Created.MergeFrom(other.Created);
      }
      if (other.updated_ != null) {
        if (updated_ == null) {
          Updated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Updated.MergeFrom(other.Updated);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Uid = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            if (localizedName_ == null) {
              LocalizedName = new global::PassKit.Grpc.LocalizedString();
            }
            input.ReadMessage(LocalizedName);
            break;
          }
          case 42: {
            FinePrint = input.ReadString();
            break;
          }
          case 50: {
            if (localizedFinePrint_ == null) {
              LocalizedFinePrint = new global::PassKit.Grpc.LocalizedString();
            }
            input.ReadMessage(LocalizedFinePrint);
            break;
          }
          case 56: {
            AutoInvalidateTicketsUponRedemption = (global::PassKit.Grpc.Toggle) input.ReadEnum();
            break;
          }
          case 64: {
            AutoInvalidateTicketsUponEventEnd = (global::PassKit.Grpc.Toggle) input.ReadEnum();
            break;
          }
          case 72: {
            AutoInvalidateTicketsUponExpiry = (global::PassKit.Grpc.Toggle) input.ReadEnum();
            break;
          }
          case 82:
          case 80: {
            status_.AddEntriesFrom(input, _repeated_status_codec);
            break;
          }
          case 90: {
            PassTypeIdentifier = input.ReadString();
            break;
          }
          case 98: {
            if (distributionSettings_ == null) {
              DistributionSettings = new global::PassKit.Grpc.DistributionSettings();
            }
            input.ReadMessage(DistributionSettings);
            break;
          }
          case 106: {
            if (created_ == null) {
              Created = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Created);
            break;
          }
          case 114: {
            if (updated_ == null) {
              Updated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Updated);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Uid = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            if (localizedName_ == null) {
              LocalizedName = new global::PassKit.Grpc.LocalizedString();
            }
            input.ReadMessage(LocalizedName);
            break;
          }
          case 42: {
            FinePrint = input.ReadString();
            break;
          }
          case 50: {
            if (localizedFinePrint_ == null) {
              LocalizedFinePrint = new global::PassKit.Grpc.LocalizedString();
            }
            input.ReadMessage(LocalizedFinePrint);
            break;
          }
          case 56: {
            AutoInvalidateTicketsUponRedemption = (global::PassKit.Grpc.Toggle) input.ReadEnum();
            break;
          }
          case 64: {
            AutoInvalidateTicketsUponEventEnd = (global::PassKit.Grpc.Toggle) input.ReadEnum();
            break;
          }
          case 72: {
            AutoInvalidateTicketsUponExpiry = (global::PassKit.Grpc.Toggle) input.ReadEnum();
            break;
          }
          case 82:
          case 80: {
            status_.AddEntriesFrom(ref input, _repeated_status_codec);
            break;
          }
          case 90: {
            PassTypeIdentifier = input.ReadString();
            break;
          }
          case 98: {
            if (distributionSettings_ == null) {
              DistributionSettings = new global::PassKit.Grpc.DistributionSettings();
            }
            input.ReadMessage(DistributionSettings);
            break;
          }
          case 106: {
            if (created_ == null) {
              Created = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Created);
            break;
          }
          case 114: {
            if (updated_ == null) {
              Updated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Updated);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProductionAnalyticsResponse : pb::IMessage<ProductionAnalyticsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProductionAnalyticsResponse> _parser = new pb::MessageParser<ProductionAnalyticsResponse>(() => new ProductionAnalyticsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProductionAnalyticsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PassKit.Grpc.EventTickets.ProductionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductionAnalyticsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductionAnalyticsResponse(ProductionAnalyticsResponse other) : this() {
      period_ = other.period_;
      redeemed_ = other.redeemed_;
      devices_ = other.devices_ != null ? other.devices_.Clone() : null;
      sources_ = other.sources_.Clone();
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductionAnalyticsResponse Clone() {
      return new ProductionAnalyticsResponse(this);
    }

    /// <summary>Field number for the "period" field.</summary>
    public const int PeriodFieldNumber = 1;
    private global::PassKit.Grpc.Period period_ = global::PassKit.Grpc.Period.Day;
    /// <summary>
    /// Period unit of data returned (day, month or year).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PassKit.Grpc.Period Period {
      get { return period_; }
      set {
        period_ = value;
      }
    }

    /// <summary>Field number for the "redeemed" field.</summary>
    public const int RedeemedFieldNumber = 2;
    private uint redeemed_;
    /// <summary>
    /// Passes redeemed in this period.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Redeemed {
      get { return redeemed_; }
      set {
        redeemed_ = value;
      }
    }

    /// <summary>Field number for the "devices" field.</summary>
    public const int DevicesFieldNumber = 3;
    private global::PassKit.Grpc.DeviceBreakdown devices_;
    /// <summary>
    /// Total number of pass redeemed for each device type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PassKit.Grpc.DeviceBreakdown Devices {
      get { return devices_; }
      set {
        devices_ = value;
      }
    }

    /// <summary>Field number for the "sources" field.</summary>
    public const int SourcesFieldNumber = 4;
    private static readonly pbc::MapField<string, uint>.Codec _map_sources_codec
        = new pbc::MapField<string, uint>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForUInt32(16, 0), 34);
    private readonly pbc::MapField<string, uint> sources_ = new pbc::MapField<string, uint>();
    /// <summary>
    /// Total number of pass redeemed for each distribution source.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, uint> Sources {
      get { return sources_; }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 5;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.ChartDataPoints> _repeated_data_codec
        = pb::FieldCodec.ForMessage(42, global::PassKit.Grpc.ChartDataPoints.Parser);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.ChartDataPoints> data_ = new pbc::RepeatedField<global::PassKit.Grpc.ChartDataPoints>();
    /// <summary>
    /// Breakdown of data by day, month or year.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.ChartDataPoints> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProductionAnalyticsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProductionAnalyticsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Period != other.Period) return false;
      if (Redeemed != other.Redeemed) return false;
      if (!object.Equals(Devices, other.Devices)) return false;
      if (!Sources.Equals(other.Sources)) return false;
      if(!data_.Equals(other.data_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Period != global::PassKit.Grpc.Period.Day) hash ^= Period.GetHashCode();
      if (Redeemed != 0) hash ^= Redeemed.GetHashCode();
      if (devices_ != null) hash ^= Devices.GetHashCode();
      hash ^= Sources.GetHashCode();
      hash ^= data_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Period != global::PassKit.Grpc.Period.Day) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Period);
      }
      if (Redeemed != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Redeemed);
      }
      if (devices_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Devices);
      }
      sources_.WriteTo(output, _map_sources_codec);
      data_.WriteTo(output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Period != global::PassKit.Grpc.Period.Day) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Period);
      }
      if (Redeemed != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Redeemed);
      }
      if (devices_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Devices);
      }
      sources_.WriteTo(ref output, _map_sources_codec);
      data_.WriteTo(ref output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Period != global::PassKit.Grpc.Period.Day) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Period);
      }
      if (Redeemed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Redeemed);
      }
      if (devices_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Devices);
      }
      size += sources_.CalculateSize(_map_sources_codec);
      size += data_.CalculateSize(_repeated_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProductionAnalyticsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Period != global::PassKit.Grpc.Period.Day) {
        Period = other.Period;
      }
      if (other.Redeemed != 0) {
        Redeemed = other.Redeemed;
      }
      if (other.devices_ != null) {
        if (devices_ == null) {
          Devices = new global::PassKit.Grpc.DeviceBreakdown();
        }
        Devices.MergeFrom(other.Devices);
      }
      sources_.Add(other.sources_);
      data_.Add(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Period = (global::PassKit.Grpc.Period) input.ReadEnum();
            break;
          }
          case 16: {
            Redeemed = input.ReadUInt32();
            break;
          }
          case 26: {
            if (devices_ == null) {
              Devices = new global::PassKit.Grpc.DeviceBreakdown();
            }
            input.ReadMessage(Devices);
            break;
          }
          case 34: {
            sources_.AddEntriesFrom(input, _map_sources_codec);
            break;
          }
          case 42: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Period = (global::PassKit.Grpc.Period) input.ReadEnum();
            break;
          }
          case 16: {
            Redeemed = input.ReadUInt32();
            break;
          }
          case 26: {
            if (devices_ == null) {
              Devices = new global::PassKit.Grpc.DeviceBreakdown();
            }
            input.ReadMessage(Devices);
            break;
          }
          case 34: {
            sources_.AddEntriesFrom(ref input, _map_sources_codec);
            break;
          }
          case 42: {
            data_.AddEntriesFrom(ref input, _repeated_data_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Contains payload for copying a Production.
  /// </summary>
  public sealed partial class ProductionCopyRequest : pb::IMessage<ProductionCopyRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProductionCopyRequest> _parser = new pb::MessageParser<ProductionCopyRequest>(() => new ProductionCopyRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProductionCopyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PassKit.Grpc.EventTickets.ProductionReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductionCopyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductionCopyRequest(ProductionCopyRequest other) : this() {
      id_ = other.id_;
      uid_ = other.uid_;
      name_ = other.name_;
      status_ = other.status_.Clone();
      passTypeIdentifier_ = other.passTypeIdentifier_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductionCopyRequest Clone() {
      return new ProductionCopyRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    /// uuid of the Production to copy.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 2;
    private string uid_ = "";
    /// <summary>
    /// User generated production id; unique within the account.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    /// <summary>
    /// Optional name for the new Production.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 4;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.ProjectStatus> _repeated_status_codec
        = pb::FieldCodec.ForEnum(34, x => (int) x, x => (global::PassKit.Grpc.ProjectStatus) x);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.ProjectStatus> status_ = new pbc::RepeatedField<global::PassKit.Grpc.ProjectStatus>();
    /// <summary>
    /// Status to set the copied Production to.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.ProjectStatus> Status {
      get { return status_; }
    }

    /// <summary>Field number for the "passTypeIdentifier" field.</summary>
    public const int PassTypeIdentifierFieldNumber = 5;
    private string passTypeIdentifier_ = "";
    /// <summary>
    /// Can optionally be provided if setting status to published (requires a prod cert).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PassTypeIdentifier {
      get { return passTypeIdentifier_; }
      set {
        passTypeIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProductionCopyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProductionCopyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Uid != other.Uid) return false;
      if (Name != other.Name) return false;
      if(!status_.Equals(other.status_)) return false;
      if (PassTypeIdentifier != other.PassTypeIdentifier) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Uid.Length != 0) hash ^= Uid.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= status_.GetHashCode();
      if (PassTypeIdentifier.Length != 0) hash ^= PassTypeIdentifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Uid);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      status_.WriteTo(output, _repeated_status_codec);
      if (PassTypeIdentifier.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PassTypeIdentifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Uid);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      status_.WriteTo(ref output, _repeated_status_codec);
      if (PassTypeIdentifier.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PassTypeIdentifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += status_.CalculateSize(_repeated_status_codec);
      if (PassTypeIdentifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PassTypeIdentifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProductionCopyRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Uid.Length != 0) {
        Uid = other.Uid;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      status_.Add(other.status_);
      if (other.PassTypeIdentifier.Length != 0) {
        PassTypeIdentifier = other.PassTypeIdentifier;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Uid = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34:
          case 32: {
            status_.AddEntriesFrom(input, _repeated_status_codec);
            break;
          }
          case 42: {
            PassTypeIdentifier = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Uid = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34:
          case 32: {
            status_.AddEntriesFrom(ref input, _repeated_status_codec);
            break;
          }
          case 42: {
            PassTypeIdentifier = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProductionLimitedFieldsResponse : pb::IMessage<ProductionLimitedFieldsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProductionLimitedFieldsResponse> _parser = new pb::MessageParser<ProductionLimitedFieldsResponse>(() => new ProductionLimitedFieldsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProductionLimitedFieldsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PassKit.Grpc.EventTickets.ProductionReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductionLimitedFieldsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductionLimitedFieldsResponse(ProductionLimitedFieldsResponse other) : this() {
      id_ = other.id_;
      uid_ = other.uid_;
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductionLimitedFieldsResponse Clone() {
      return new ProductionLimitedFieldsResponse(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    /// PassKit generated production id (22 characters).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 2;
    private string uid_ = "";
    /// <summary>
    /// User generated production id; unique within the account.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    /// <summary>
    /// Name of the production (i.e. Les Miserables, The Lion King, Avengers, etc).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProductionLimitedFieldsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProductionLimitedFieldsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Uid != other.Uid) return false;
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Uid.Length != 0) hash ^= Uid.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Uid);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Uid);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProductionLimitedFieldsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Uid.Length != 0) {
        Uid = other.Uid;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Uid = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Uid = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
