// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: io/common/tracking.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PassKit.Grpc {

  /// <summary>Holder for reflection information generated from io/common/tracking.proto</summary>
  public static partial class TrackingReflection {

    #region Descriptor
    /// <summary>File descriptor for io/common/tracking.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TrackingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhpby9jb21tb24vdHJhY2tpbmcucHJvdG8SAmlvIpADChVGYWNlYm9va1Bp",
            "eGVsU2V0dGluZ3MSDwoHcGl4ZWxJZBgBIAEoCRI7CiBkYXRhQ29sbGVjdGlv",
            "blBhZ2VTdGFuZGFyZEV2ZW50cxgCIAMoCzIRLmlvLlN0YW5kYXJkRXZlbnQS",
            "NwoeZGF0YUNvbGxlY3Rpb25QYWdlQ3VzdG9tRXZlbnRzGAMgAygLMg8uaW8u",
            "Q3VzdG9tRXZlbnQSMQoWcGFzc1BhZ2VTdGFuZGFyZEV2ZW50cxgEIAMoCzIR",
            "LmlvLlN0YW5kYXJkRXZlbnQSLQoUcGFzc1BhZ2VDdXN0b21FdmVudHMYBSAD",
            "KAsyDy5pby5DdXN0b21FdmVudBJICi1jdXN0b21lckluaXRpYXRlZFJlZGVt",
            "cHRpb25QYWdlU3RhbmRhcmRFdmVudHMYBiADKAsyES5pby5TdGFuZGFyZEV2",
            "ZW50EkQKK2N1c3RvbWVySW5pdGlhdGVkUmVkZW1wdGlvblBhZ2VDdXN0b21F",
            "dmVudHMYByADKAsyDy5pby5DdXN0b21FdmVudCJSCg1TdGFuZGFyZEV2ZW50",
            "EicKBWV2ZW50GAEgASgOMhguaW8uRmJQaXhlbFN0YW5kYXJkRXZlbnQSEgoK",
            "cHJvcGVydGllcxgDIAEoCUoECAIQAyI2CgtDdXN0b21FdmVudBINCgVldmVu",
            "dBgBIAEoCRISCgpwcm9wZXJ0aWVzGAMgASgJSgQIAhADIqACChdHb29nbGVB",
            "bmFseXRpY3NTZXR0aW5ncxITCgt0cmFja2luZ0lkcxgBIAMoCRJMChhkYXRh",
            "Q29sbGVjdGlvblBhZ2VFdmVudHMYAiADKA4yKi5pby5Hb29nbGVBbmFseXRp",
            "Y3NEYXRhQ29sbGVjdGlvblBhZ2VFdmVudBJEChRwYXNzUmVuZGVyUGFnZUV2",
            "ZW50cxgDIAMoDjImLmlvLkdvb2dsZUFuYWx5dGljc1Bhc3NSZW5kZXJQYWdl",
            "RXZlbnQSXAobY3VzdG9tZXJJbml0aWF0ZWRSZWRlbXB0aW9uGAQgAygOMjcu",
            "aW8uR29vZ2xlQW5hbHl0aWNzQ3VzdG9tZXJJbml0aWF0ZWRSZWRlbXB0aW9u",
            "UGFnZUV2ZW50IooBChBUcmFja2luZ1NldHRpbmdzEjgKFWZhY2Vib29rUGl4",
            "ZWxTZXR0aW5ncxgBIAEoCzIZLmlvLkZhY2Vib29rUGl4ZWxTZXR0aW5ncxI8",
            "Chdnb29nbGVBbmFseXRpY3NTZXR0aW5ncxgCIAEoCzIbLmlvLkdvb2dsZUFu",
            "YWx5dGljc1NldHRpbmdzKv4CChRGYlBpeGVsU3RhbmRhcmRFdmVudBIhCh1G",
            "QlBfU1RBTkRBUkRfRVZFTlRfRE9fTk9UX1VTRRAAEiAKHEZCUF9TVEFOREFS",
            "RF9FVkVOVF9QQUdFX1ZJRVcQARIsCihGQlBfU1RBTkRBUkRfRVZFTlRfQ09N",
            "UExFVEVfUkVHSVNUUkFUSU9OEAISGwoXRkJQX1NUQU5EQVJEX0VWRU5UX0xF",
            "QUQQAxIfChtGQlBfU1RBTkRBUkRfRVZFTlRfUFVSQ0hBU0UQBBIfChtGQlBf",
            "U1RBTkRBUkRfRVZFTlRfU0NIRURVTEUQBRIiCh5GQlBfU1RBTkRBUkRfRVZF",
            "TlRfU1RBUlRfVFJJQUwQBhIpCiVGQlBfU1RBTkRBUkRfRVZFTlRfU1VCTUlU",
            "X0FQUExJQ0FUSU9OEAcSIAocRkJQX1NUQU5EQVJEX0VWRU5UX1NVQlNDUklC",
            "RRAIEiMKH0ZCUF9TVEFOREFSRF9FVkVOVF9WSUVXX0NPTlRFTlQQCSp8CiZH",
            "b29nbGVBbmFseXRpY3NEYXRhQ29sbGVjdGlvblBhZ2VFdmVudBIaChZHQV9E",
            "Q19FVkVOVF9ET19OT1RfVVNFEAASGQoVR0FfRENfRVZFTlRfUEFHRV9WSUVX",
            "EAESGwoXR0FfRENfRVZFTlRfU1VCTUlUX0ZPUk0QAiqCAgoiR29vZ2xlQW5h",
            "bHl0aWNzUGFzc1JlbmRlclBhZ2VFdmVudBIaChZHQV9QUF9FVkVOVF9ET19O",
            "T1RfVVNFEAASGQoVR0FfUFBfRVZFTlRfUEFHRV9WSUVXEAESKQolR0FfUFBf",
            "RVZFTlRfQUREX1RPX0FQUExFX1dBTExFVF9DTElDSxACEi8KK0dBX1BQX0VW",
            "RU5UX1ZJRVdfUEFTU19JTl9BUFBMRV9XQUxMRVRfQ0xJQ0sQAxIoCiRHQV9Q",
            "UF9FVkVOVF9TQVZFX1RPX0dPT0dMRV9QQVlfQ0xJQ0sQBBIfChtHQV9QUF9F",
            "VkVOVF9DSEFOR0VfTEFOR1VBR0UQBSqKAQozR29vZ2xlQW5hbHl0aWNzQ3Vz",
            "dG9tZXJJbml0aWF0ZWRSZWRlbXB0aW9uUGFnZUV2ZW50EhwKGEdBX0NJUlBf",
            "RVZFTlRfRE9fTk9UX1VTRRAAEhsKF0dBX0NJUlBfRVZFTlRfUEFHRV9WSUVX",
            "EAESGAoUR0FfQ0lSUF9FVkVOVF9SRURFRU0QAkJHChBjb20ucGFzc2tpdC5n",
            "cnBjWiRzdGFzaC5wYXNza2l0LmNvbS9pby9tb2RlbC9zZGsvZ28vaW+qAgxQ",
            "YXNzS2l0LkdycGNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PassKit.Grpc.FbPixelStandardEvent), typeof(global::PassKit.Grpc.GoogleAnalyticsDataCollectionPageEvent), typeof(global::PassKit.Grpc.GoogleAnalyticsPassRenderPageEvent), typeof(global::PassKit.Grpc.GoogleAnalyticsCustomerInitiatedRedemptionPageEvent), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PassKit.Grpc.FacebookPixelSettings), global::PassKit.Grpc.FacebookPixelSettings.Parser, new[]{ "PixelId", "DataCollectionPageStandardEvents", "DataCollectionPageCustomEvents", "PassPageStandardEvents", "PassPageCustomEvents", "CustomerInitiatedRedemptionPageStandardEvents", "CustomerInitiatedRedemptionPageCustomEvents" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PassKit.Grpc.StandardEvent), global::PassKit.Grpc.StandardEvent.Parser, new[]{ "Event", "Properties" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PassKit.Grpc.CustomEvent), global::PassKit.Grpc.CustomEvent.Parser, new[]{ "Event", "Properties" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PassKit.Grpc.GoogleAnalyticsSettings), global::PassKit.Grpc.GoogleAnalyticsSettings.Parser, new[]{ "TrackingIds", "DataCollectionPageEvents", "PassRenderPageEvents", "CustomerInitiatedRedemption" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PassKit.Grpc.TrackingSettings), global::PassKit.Grpc.TrackingSettings.Parser, new[]{ "FacebookPixelSettings", "GoogleAnalyticsSettings" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Standard Facebook Pixel events that we support
  /// </summary>
  public enum FbPixelStandardEvent {
    [pbr::OriginalName("FBP_STANDARD_EVENT_DO_NOT_USE")] FbpStandardEventDoNotUse = 0,
    /// <summary>
    /// This is the default pixel tracking page visits.
    /// </summary>
    [pbr::OriginalName("FBP_STANDARD_EVENT_PAGE_VIEW")] FbpStandardEventPageView = 1,
    /// <summary>
    /// When a registration form is completed.
    /// </summary>
    [pbr::OriginalName("FBP_STANDARD_EVENT_COMPLETE_REGISTRATION")] FbpStandardEventCompleteRegistration = 2,
    /// <summary>
    /// When a sign up is completed.
    /// </summary>
    [pbr::OriginalName("FBP_STANDARD_EVENT_LEAD")] FbpStandardEventLead = 3,
    /// <summary>
    /// When a purchase is made or checkout flow is completed.
    /// </summary>
    [pbr::OriginalName("FBP_STANDARD_EVENT_PURCHASE")] FbpStandardEventPurchase = 4,
    /// <summary>
    /// When a person books an appointment to visit one of your locations.
    /// </summary>
    [pbr::OriginalName("FBP_STANDARD_EVENT_SCHEDULE")] FbpStandardEventSchedule = 5,
    /// <summary>
    /// When a person starts a free trial of a product or service you offer.
    /// </summary>
    [pbr::OriginalName("FBP_STANDARD_EVENT_START_TRIAL")] FbpStandardEventStartTrial = 6,
    /// <summary>
    /// When a person applies for a product, service, or program you offer.
    /// </summary>
    [pbr::OriginalName("FBP_STANDARD_EVENT_SUBMIT_APPLICATION")] FbpStandardEventSubmitApplication = 7,
    /// <summary>
    /// When a person applies to a start a paid subscription for a product or service you offer.
    /// </summary>
    [pbr::OriginalName("FBP_STANDARD_EVENT_SUBSCRIBE")] FbpStandardEventSubscribe = 8,
    /// <summary>
    /// A visit to a web page you care about (for example, a product page or landing page). ViewContent tells you if someone visits a web page's URL, but not what they see or do on that page.
    /// </summary>
    [pbr::OriginalName("FBP_STANDARD_EVENT_VIEW_CONTENT")] FbpStandardEventViewContent = 9,
  }

  public enum GoogleAnalyticsDataCollectionPageEvent {
    [pbr::OriginalName("GA_DC_EVENT_DO_NOT_USE")] GaDcEventDoNotUse = 0,
    /// <summary>
    /// This is the default GA even tracking page visits.
    /// </summary>
    [pbr::OriginalName("GA_DC_EVENT_PAGE_VIEW")] GaDcEventPageView = 1,
    /// <summary>
    /// When a user submits the data collection form.
    /// </summary>
    [pbr::OriginalName("GA_DC_EVENT_SUBMIT_FORM")] GaDcEventSubmitForm = 2,
  }

  public enum GoogleAnalyticsPassRenderPageEvent {
    [pbr::OriginalName("GA_PP_EVENT_DO_NOT_USE")] GaPpEventDoNotUse = 0,
    /// <summary>
    /// This is the default GA event tracking page visits.
    /// </summary>
    [pbr::OriginalName("GA_PP_EVENT_PAGE_VIEW")] GaPpEventPageView = 1,
    /// <summary>
    /// When a user clicks the Add to Apple Wallet button.
    /// </summary>
    [pbr::OriginalName("GA_PP_EVENT_ADD_TO_APPLE_WALLET_CLICK")] GaPpEventAddToAppleWalletClick = 2,
    /// <summary>
    /// When a user clicks the view pass in Apple Wallet button.
    /// </summary>
    [pbr::OriginalName("GA_PP_EVENT_VIEW_PASS_IN_APPLE_WALLET_CLICK")] GaPpEventViewPassInAppleWalletClick = 3,
    /// <summary>
    /// When a user clicks the Save to Google Pay button.
    /// </summary>
    [pbr::OriginalName("GA_PP_EVENT_SAVE_TO_GOOGLE_PAY_CLICK")] GaPpEventSaveToGooglePayClick = 4,
    /// <summary>
    /// When a user switches the language.
    /// </summary>
    [pbr::OriginalName("GA_PP_EVENT_CHANGE_LANGUAGE")] GaPpEventChangeLanguage = 5,
  }

  public enum GoogleAnalyticsCustomerInitiatedRedemptionPageEvent {
    [pbr::OriginalName("GA_CIRP_EVENT_DO_NOT_USE")] GaCirpEventDoNotUse = 0,
    /// <summary>
    /// This is the default GA event tracking page visits.
    /// </summary>
    [pbr::OriginalName("GA_CIRP_EVENT_PAGE_VIEW")] GaCirpEventPageView = 1,
    /// <summary>
    /// When a user redeems the coupon.
    /// </summary>
    [pbr::OriginalName("GA_CIRP_EVENT_REDEEM")] GaCirpEventRedeem = 2,
  }

  #endregion

  #region Messages
  public sealed partial class FacebookPixelSettings : pb::IMessage<FacebookPixelSettings>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FacebookPixelSettings> _parser = new pb::MessageParser<FacebookPixelSettings>(() => new FacebookPixelSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FacebookPixelSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PassKit.Grpc.TrackingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FacebookPixelSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FacebookPixelSettings(FacebookPixelSettings other) : this() {
      pixelId_ = other.pixelId_;
      dataCollectionPageStandardEvents_ = other.dataCollectionPageStandardEvents_.Clone();
      dataCollectionPageCustomEvents_ = other.dataCollectionPageCustomEvents_.Clone();
      passPageStandardEvents_ = other.passPageStandardEvents_.Clone();
      passPageCustomEvents_ = other.passPageCustomEvents_.Clone();
      customerInitiatedRedemptionPageStandardEvents_ = other.customerInitiatedRedemptionPageStandardEvents_.Clone();
      customerInitiatedRedemptionPageCustomEvents_ = other.customerInitiatedRedemptionPageCustomEvents_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FacebookPixelSettings Clone() {
      return new FacebookPixelSettings(this);
    }

    /// <summary>Field number for the "pixelId" field.</summary>
    public const int PixelIdFieldNumber = 1;
    private string pixelId_ = "";
    /// <summary>
    /// The Facebook Pixel ID of the account.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PixelId {
      get { return pixelId_; }
      set {
        pixelId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dataCollectionPageStandardEvents" field.</summary>
    public const int DataCollectionPageStandardEventsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.StandardEvent> _repeated_dataCollectionPageStandardEvents_codec
        = pb::FieldCodec.ForMessage(18, global::PassKit.Grpc.StandardEvent.Parser);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.StandardEvent> dataCollectionPageStandardEvents_ = new pbc::RepeatedField<global::PassKit.Grpc.StandardEvent>();
    /// <summary>
    /// List of standard events for the data collection page
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.StandardEvent> DataCollectionPageStandardEvents {
      get { return dataCollectionPageStandardEvents_; }
    }

    /// <summary>Field number for the "dataCollectionPageCustomEvents" field.</summary>
    public const int DataCollectionPageCustomEventsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.CustomEvent> _repeated_dataCollectionPageCustomEvents_codec
        = pb::FieldCodec.ForMessage(26, global::PassKit.Grpc.CustomEvent.Parser);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.CustomEvent> dataCollectionPageCustomEvents_ = new pbc::RepeatedField<global::PassKit.Grpc.CustomEvent>();
    /// <summary>
    /// List of custom events for the data collection page
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.CustomEvent> DataCollectionPageCustomEvents {
      get { return dataCollectionPageCustomEvents_; }
    }

    /// <summary>Field number for the "passPageStandardEvents" field.</summary>
    public const int PassPageStandardEventsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.StandardEvent> _repeated_passPageStandardEvents_codec
        = pb::FieldCodec.ForMessage(34, global::PassKit.Grpc.StandardEvent.Parser);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.StandardEvent> passPageStandardEvents_ = new pbc::RepeatedField<global::PassKit.Grpc.StandardEvent>();
    /// <summary>
    /// List of standard events for the pass render page
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.StandardEvent> PassPageStandardEvents {
      get { return passPageStandardEvents_; }
    }

    /// <summary>Field number for the "passPageCustomEvents" field.</summary>
    public const int PassPageCustomEventsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.CustomEvent> _repeated_passPageCustomEvents_codec
        = pb::FieldCodec.ForMessage(42, global::PassKit.Grpc.CustomEvent.Parser);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.CustomEvent> passPageCustomEvents_ = new pbc::RepeatedField<global::PassKit.Grpc.CustomEvent>();
    /// <summary>
    /// List of custom events for the pass render page
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.CustomEvent> PassPageCustomEvents {
      get { return passPageCustomEvents_; }
    }

    /// <summary>Field number for the "customerInitiatedRedemptionPageStandardEvents" field.</summary>
    public const int CustomerInitiatedRedemptionPageStandardEventsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.StandardEvent> _repeated_customerInitiatedRedemptionPageStandardEvents_codec
        = pb::FieldCodec.ForMessage(50, global::PassKit.Grpc.StandardEvent.Parser);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.StandardEvent> customerInitiatedRedemptionPageStandardEvents_ = new pbc::RepeatedField<global::PassKit.Grpc.StandardEvent>();
    /// <summary>
    /// List of standard events for the coupon customer initiated redemption page
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.StandardEvent> CustomerInitiatedRedemptionPageStandardEvents {
      get { return customerInitiatedRedemptionPageStandardEvents_; }
    }

    /// <summary>Field number for the "customerInitiatedRedemptionPageCustomEvents" field.</summary>
    public const int CustomerInitiatedRedemptionPageCustomEventsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.CustomEvent> _repeated_customerInitiatedRedemptionPageCustomEvents_codec
        = pb::FieldCodec.ForMessage(58, global::PassKit.Grpc.CustomEvent.Parser);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.CustomEvent> customerInitiatedRedemptionPageCustomEvents_ = new pbc::RepeatedField<global::PassKit.Grpc.CustomEvent>();
    /// <summary>
    /// List of custom events for the coupon customer initiated redemption page
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.CustomEvent> CustomerInitiatedRedemptionPageCustomEvents {
      get { return customerInitiatedRedemptionPageCustomEvents_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FacebookPixelSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FacebookPixelSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PixelId != other.PixelId) return false;
      if(!dataCollectionPageStandardEvents_.Equals(other.dataCollectionPageStandardEvents_)) return false;
      if(!dataCollectionPageCustomEvents_.Equals(other.dataCollectionPageCustomEvents_)) return false;
      if(!passPageStandardEvents_.Equals(other.passPageStandardEvents_)) return false;
      if(!passPageCustomEvents_.Equals(other.passPageCustomEvents_)) return false;
      if(!customerInitiatedRedemptionPageStandardEvents_.Equals(other.customerInitiatedRedemptionPageStandardEvents_)) return false;
      if(!customerInitiatedRedemptionPageCustomEvents_.Equals(other.customerInitiatedRedemptionPageCustomEvents_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PixelId.Length != 0) hash ^= PixelId.GetHashCode();
      hash ^= dataCollectionPageStandardEvents_.GetHashCode();
      hash ^= dataCollectionPageCustomEvents_.GetHashCode();
      hash ^= passPageStandardEvents_.GetHashCode();
      hash ^= passPageCustomEvents_.GetHashCode();
      hash ^= customerInitiatedRedemptionPageStandardEvents_.GetHashCode();
      hash ^= customerInitiatedRedemptionPageCustomEvents_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PixelId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PixelId);
      }
      dataCollectionPageStandardEvents_.WriteTo(output, _repeated_dataCollectionPageStandardEvents_codec);
      dataCollectionPageCustomEvents_.WriteTo(output, _repeated_dataCollectionPageCustomEvents_codec);
      passPageStandardEvents_.WriteTo(output, _repeated_passPageStandardEvents_codec);
      passPageCustomEvents_.WriteTo(output, _repeated_passPageCustomEvents_codec);
      customerInitiatedRedemptionPageStandardEvents_.WriteTo(output, _repeated_customerInitiatedRedemptionPageStandardEvents_codec);
      customerInitiatedRedemptionPageCustomEvents_.WriteTo(output, _repeated_customerInitiatedRedemptionPageCustomEvents_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PixelId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PixelId);
      }
      dataCollectionPageStandardEvents_.WriteTo(ref output, _repeated_dataCollectionPageStandardEvents_codec);
      dataCollectionPageCustomEvents_.WriteTo(ref output, _repeated_dataCollectionPageCustomEvents_codec);
      passPageStandardEvents_.WriteTo(ref output, _repeated_passPageStandardEvents_codec);
      passPageCustomEvents_.WriteTo(ref output, _repeated_passPageCustomEvents_codec);
      customerInitiatedRedemptionPageStandardEvents_.WriteTo(ref output, _repeated_customerInitiatedRedemptionPageStandardEvents_codec);
      customerInitiatedRedemptionPageCustomEvents_.WriteTo(ref output, _repeated_customerInitiatedRedemptionPageCustomEvents_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PixelId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PixelId);
      }
      size += dataCollectionPageStandardEvents_.CalculateSize(_repeated_dataCollectionPageStandardEvents_codec);
      size += dataCollectionPageCustomEvents_.CalculateSize(_repeated_dataCollectionPageCustomEvents_codec);
      size += passPageStandardEvents_.CalculateSize(_repeated_passPageStandardEvents_codec);
      size += passPageCustomEvents_.CalculateSize(_repeated_passPageCustomEvents_codec);
      size += customerInitiatedRedemptionPageStandardEvents_.CalculateSize(_repeated_customerInitiatedRedemptionPageStandardEvents_codec);
      size += customerInitiatedRedemptionPageCustomEvents_.CalculateSize(_repeated_customerInitiatedRedemptionPageCustomEvents_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FacebookPixelSettings other) {
      if (other == null) {
        return;
      }
      if (other.PixelId.Length != 0) {
        PixelId = other.PixelId;
      }
      dataCollectionPageStandardEvents_.Add(other.dataCollectionPageStandardEvents_);
      dataCollectionPageCustomEvents_.Add(other.dataCollectionPageCustomEvents_);
      passPageStandardEvents_.Add(other.passPageStandardEvents_);
      passPageCustomEvents_.Add(other.passPageCustomEvents_);
      customerInitiatedRedemptionPageStandardEvents_.Add(other.customerInitiatedRedemptionPageStandardEvents_);
      customerInitiatedRedemptionPageCustomEvents_.Add(other.customerInitiatedRedemptionPageCustomEvents_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PixelId = input.ReadString();
            break;
          }
          case 18: {
            dataCollectionPageStandardEvents_.AddEntriesFrom(input, _repeated_dataCollectionPageStandardEvents_codec);
            break;
          }
          case 26: {
            dataCollectionPageCustomEvents_.AddEntriesFrom(input, _repeated_dataCollectionPageCustomEvents_codec);
            break;
          }
          case 34: {
            passPageStandardEvents_.AddEntriesFrom(input, _repeated_passPageStandardEvents_codec);
            break;
          }
          case 42: {
            passPageCustomEvents_.AddEntriesFrom(input, _repeated_passPageCustomEvents_codec);
            break;
          }
          case 50: {
            customerInitiatedRedemptionPageStandardEvents_.AddEntriesFrom(input, _repeated_customerInitiatedRedemptionPageStandardEvents_codec);
            break;
          }
          case 58: {
            customerInitiatedRedemptionPageCustomEvents_.AddEntriesFrom(input, _repeated_customerInitiatedRedemptionPageCustomEvents_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PixelId = input.ReadString();
            break;
          }
          case 18: {
            dataCollectionPageStandardEvents_.AddEntriesFrom(ref input, _repeated_dataCollectionPageStandardEvents_codec);
            break;
          }
          case 26: {
            dataCollectionPageCustomEvents_.AddEntriesFrom(ref input, _repeated_dataCollectionPageCustomEvents_codec);
            break;
          }
          case 34: {
            passPageStandardEvents_.AddEntriesFrom(ref input, _repeated_passPageStandardEvents_codec);
            break;
          }
          case 42: {
            passPageCustomEvents_.AddEntriesFrom(ref input, _repeated_passPageCustomEvents_codec);
            break;
          }
          case 50: {
            customerInitiatedRedemptionPageStandardEvents_.AddEntriesFrom(ref input, _repeated_customerInitiatedRedemptionPageStandardEvents_codec);
            break;
          }
          case 58: {
            customerInitiatedRedemptionPageCustomEvents_.AddEntriesFrom(ref input, _repeated_customerInitiatedRedemptionPageCustomEvents_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StandardEvent : pb::IMessage<StandardEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StandardEvent> _parser = new pb::MessageParser<StandardEvent>(() => new StandardEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StandardEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PassKit.Grpc.TrackingReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StandardEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StandardEvent(StandardEvent other) : this() {
      event_ = other.event_;
      properties_ = other.properties_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StandardEvent Clone() {
      return new StandardEvent(this);
    }

    /// <summary>Field number for the "event" field.</summary>
    public const int EventFieldNumber = 1;
    private global::PassKit.Grpc.FbPixelStandardEvent event_ = global::PassKit.Grpc.FbPixelStandardEvent.FbpStandardEventDoNotUse;
    /// <summary>
    /// Standard event
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PassKit.Grpc.FbPixelStandardEvent Event {
      get { return event_; }
      set {
        event_ = value;
      }
    }

    /// <summary>Field number for the "properties" field.</summary>
    public const int PropertiesFieldNumber = 3;
    private string properties_ = "";
    /// <summary>
    /// Optional event properties
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Properties {
      get { return properties_; }
      set {
        properties_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StandardEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StandardEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Event != other.Event) return false;
      if (Properties != other.Properties) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Event != global::PassKit.Grpc.FbPixelStandardEvent.FbpStandardEventDoNotUse) hash ^= Event.GetHashCode();
      if (Properties.Length != 0) hash ^= Properties.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Event != global::PassKit.Grpc.FbPixelStandardEvent.FbpStandardEventDoNotUse) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Event);
      }
      if (Properties.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Properties);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Event != global::PassKit.Grpc.FbPixelStandardEvent.FbpStandardEventDoNotUse) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Event);
      }
      if (Properties.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Properties);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Event != global::PassKit.Grpc.FbPixelStandardEvent.FbpStandardEventDoNotUse) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Event);
      }
      if (Properties.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Properties);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StandardEvent other) {
      if (other == null) {
        return;
      }
      if (other.Event != global::PassKit.Grpc.FbPixelStandardEvent.FbpStandardEventDoNotUse) {
        Event = other.Event;
      }
      if (other.Properties.Length != 0) {
        Properties = other.Properties;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Event = (global::PassKit.Grpc.FbPixelStandardEvent) input.ReadEnum();
            break;
          }
          case 26: {
            Properties = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Event = (global::PassKit.Grpc.FbPixelStandardEvent) input.ReadEnum();
            break;
          }
          case 26: {
            Properties = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CustomEvent : pb::IMessage<CustomEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CustomEvent> _parser = new pb::MessageParser<CustomEvent>(() => new CustomEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CustomEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PassKit.Grpc.TrackingReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomEvent(CustomEvent other) : this() {
      event_ = other.event_;
      properties_ = other.properties_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomEvent Clone() {
      return new CustomEvent(this);
    }

    /// <summary>Field number for the "event" field.</summary>
    public const int EventFieldNumber = 1;
    private string event_ = "";
    /// <summary>
    /// Custom event name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Event {
      get { return event_; }
      set {
        event_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "properties" field.</summary>
    public const int PropertiesFieldNumber = 3;
    private string properties_ = "";
    /// <summary>
    /// Optional event properties
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Properties {
      get { return properties_; }
      set {
        properties_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CustomEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CustomEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Event != other.Event) return false;
      if (Properties != other.Properties) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Event.Length != 0) hash ^= Event.GetHashCode();
      if (Properties.Length != 0) hash ^= Properties.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Event.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Event);
      }
      if (Properties.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Properties);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Event.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Event);
      }
      if (Properties.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Properties);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Event.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Event);
      }
      if (Properties.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Properties);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CustomEvent other) {
      if (other == null) {
        return;
      }
      if (other.Event.Length != 0) {
        Event = other.Event;
      }
      if (other.Properties.Length != 0) {
        Properties = other.Properties;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Event = input.ReadString();
            break;
          }
          case 26: {
            Properties = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Event = input.ReadString();
            break;
          }
          case 26: {
            Properties = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GoogleAnalyticsSettings : pb::IMessage<GoogleAnalyticsSettings>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GoogleAnalyticsSettings> _parser = new pb::MessageParser<GoogleAnalyticsSettings>(() => new GoogleAnalyticsSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GoogleAnalyticsSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PassKit.Grpc.TrackingReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoogleAnalyticsSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoogleAnalyticsSettings(GoogleAnalyticsSettings other) : this() {
      trackingIds_ = other.trackingIds_.Clone();
      dataCollectionPageEvents_ = other.dataCollectionPageEvents_.Clone();
      passRenderPageEvents_ = other.passRenderPageEvents_.Clone();
      customerInitiatedRedemption_ = other.customerInitiatedRedemption_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoogleAnalyticsSettings Clone() {
      return new GoogleAnalyticsSettings(this);
    }

    /// <summary>Field number for the "trackingIds" field.</summary>
    public const int TrackingIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_trackingIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> trackingIds_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// list of Google Analytics ID's to track ('UA-XXXXX-Y', 'UA-XXXXX-B', etc).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> TrackingIds {
      get { return trackingIds_; }
    }

    /// <summary>Field number for the "dataCollectionPageEvents" field.</summary>
    public const int DataCollectionPageEventsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.GoogleAnalyticsDataCollectionPageEvent> _repeated_dataCollectionPageEvents_codec
        = pb::FieldCodec.ForEnum(18, x => (int) x, x => (global::PassKit.Grpc.GoogleAnalyticsDataCollectionPageEvent) x);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.GoogleAnalyticsDataCollectionPageEvent> dataCollectionPageEvents_ = new pbc::RepeatedField<global::PassKit.Grpc.GoogleAnalyticsDataCollectionPageEvent>();
    /// <summary>
    /// Events to send to Google on the data collection page.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.GoogleAnalyticsDataCollectionPageEvent> DataCollectionPageEvents {
      get { return dataCollectionPageEvents_; }
    }

    /// <summary>Field number for the "passRenderPageEvents" field.</summary>
    public const int PassRenderPageEventsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.GoogleAnalyticsPassRenderPageEvent> _repeated_passRenderPageEvents_codec
        = pb::FieldCodec.ForEnum(26, x => (int) x, x => (global::PassKit.Grpc.GoogleAnalyticsPassRenderPageEvent) x);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.GoogleAnalyticsPassRenderPageEvent> passRenderPageEvents_ = new pbc::RepeatedField<global::PassKit.Grpc.GoogleAnalyticsPassRenderPageEvent>();
    /// <summary>
    /// Events to send to Google on the pass render page.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.GoogleAnalyticsPassRenderPageEvent> PassRenderPageEvents {
      get { return passRenderPageEvents_; }
    }

    /// <summary>Field number for the "customerInitiatedRedemption" field.</summary>
    public const int CustomerInitiatedRedemptionFieldNumber = 4;
    private static readonly pb::FieldCodec<global::PassKit.Grpc.GoogleAnalyticsCustomerInitiatedRedemptionPageEvent> _repeated_customerInitiatedRedemption_codec
        = pb::FieldCodec.ForEnum(34, x => (int) x, x => (global::PassKit.Grpc.GoogleAnalyticsCustomerInitiatedRedemptionPageEvent) x);
    private readonly pbc::RepeatedField<global::PassKit.Grpc.GoogleAnalyticsCustomerInitiatedRedemptionPageEvent> customerInitiatedRedemption_ = new pbc::RepeatedField<global::PassKit.Grpc.GoogleAnalyticsCustomerInitiatedRedemptionPageEvent>();
    /// <summary>
    /// Events to send to Google on the custom initiated redemption page.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::PassKit.Grpc.GoogleAnalyticsCustomerInitiatedRedemptionPageEvent> CustomerInitiatedRedemption {
      get { return customerInitiatedRedemption_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GoogleAnalyticsSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GoogleAnalyticsSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!trackingIds_.Equals(other.trackingIds_)) return false;
      if(!dataCollectionPageEvents_.Equals(other.dataCollectionPageEvents_)) return false;
      if(!passRenderPageEvents_.Equals(other.passRenderPageEvents_)) return false;
      if(!customerInitiatedRedemption_.Equals(other.customerInitiatedRedemption_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= trackingIds_.GetHashCode();
      hash ^= dataCollectionPageEvents_.GetHashCode();
      hash ^= passRenderPageEvents_.GetHashCode();
      hash ^= customerInitiatedRedemption_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      trackingIds_.WriteTo(output, _repeated_trackingIds_codec);
      dataCollectionPageEvents_.WriteTo(output, _repeated_dataCollectionPageEvents_codec);
      passRenderPageEvents_.WriteTo(output, _repeated_passRenderPageEvents_codec);
      customerInitiatedRedemption_.WriteTo(output, _repeated_customerInitiatedRedemption_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      trackingIds_.WriteTo(ref output, _repeated_trackingIds_codec);
      dataCollectionPageEvents_.WriteTo(ref output, _repeated_dataCollectionPageEvents_codec);
      passRenderPageEvents_.WriteTo(ref output, _repeated_passRenderPageEvents_codec);
      customerInitiatedRedemption_.WriteTo(ref output, _repeated_customerInitiatedRedemption_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += trackingIds_.CalculateSize(_repeated_trackingIds_codec);
      size += dataCollectionPageEvents_.CalculateSize(_repeated_dataCollectionPageEvents_codec);
      size += passRenderPageEvents_.CalculateSize(_repeated_passRenderPageEvents_codec);
      size += customerInitiatedRedemption_.CalculateSize(_repeated_customerInitiatedRedemption_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GoogleAnalyticsSettings other) {
      if (other == null) {
        return;
      }
      trackingIds_.Add(other.trackingIds_);
      dataCollectionPageEvents_.Add(other.dataCollectionPageEvents_);
      passRenderPageEvents_.Add(other.passRenderPageEvents_);
      customerInitiatedRedemption_.Add(other.customerInitiatedRedemption_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            trackingIds_.AddEntriesFrom(input, _repeated_trackingIds_codec);
            break;
          }
          case 18:
          case 16: {
            dataCollectionPageEvents_.AddEntriesFrom(input, _repeated_dataCollectionPageEvents_codec);
            break;
          }
          case 26:
          case 24: {
            passRenderPageEvents_.AddEntriesFrom(input, _repeated_passRenderPageEvents_codec);
            break;
          }
          case 34:
          case 32: {
            customerInitiatedRedemption_.AddEntriesFrom(input, _repeated_customerInitiatedRedemption_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            trackingIds_.AddEntriesFrom(ref input, _repeated_trackingIds_codec);
            break;
          }
          case 18:
          case 16: {
            dataCollectionPageEvents_.AddEntriesFrom(ref input, _repeated_dataCollectionPageEvents_codec);
            break;
          }
          case 26:
          case 24: {
            passRenderPageEvents_.AddEntriesFrom(ref input, _repeated_passRenderPageEvents_codec);
            break;
          }
          case 34:
          case 32: {
            customerInitiatedRedemption_.AddEntriesFrom(ref input, _repeated_customerInitiatedRedemption_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TrackingSettings : pb::IMessage<TrackingSettings>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrackingSettings> _parser = new pb::MessageParser<TrackingSettings>(() => new TrackingSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrackingSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PassKit.Grpc.TrackingReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrackingSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrackingSettings(TrackingSettings other) : this() {
      facebookPixelSettings_ = other.facebookPixelSettings_ != null ? other.facebookPixelSettings_.Clone() : null;
      googleAnalyticsSettings_ = other.googleAnalyticsSettings_ != null ? other.googleAnalyticsSettings_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrackingSettings Clone() {
      return new TrackingSettings(this);
    }

    /// <summary>Field number for the "facebookPixelSettings" field.</summary>
    public const int FacebookPixelSettingsFieldNumber = 1;
    private global::PassKit.Grpc.FacebookPixelSettings facebookPixelSettings_;
    /// <summary>
    /// Facebook Pixel settings
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PassKit.Grpc.FacebookPixelSettings FacebookPixelSettings {
      get { return facebookPixelSettings_; }
      set {
        facebookPixelSettings_ = value;
      }
    }

    /// <summary>Field number for the "googleAnalyticsSettings" field.</summary>
    public const int GoogleAnalyticsSettingsFieldNumber = 2;
    private global::PassKit.Grpc.GoogleAnalyticsSettings googleAnalyticsSettings_;
    /// <summary>
    /// Google Analytics settings
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PassKit.Grpc.GoogleAnalyticsSettings GoogleAnalyticsSettings {
      get { return googleAnalyticsSettings_; }
      set {
        googleAnalyticsSettings_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrackingSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrackingSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FacebookPixelSettings, other.FacebookPixelSettings)) return false;
      if (!object.Equals(GoogleAnalyticsSettings, other.GoogleAnalyticsSettings)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (facebookPixelSettings_ != null) hash ^= FacebookPixelSettings.GetHashCode();
      if (googleAnalyticsSettings_ != null) hash ^= GoogleAnalyticsSettings.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (facebookPixelSettings_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FacebookPixelSettings);
      }
      if (googleAnalyticsSettings_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GoogleAnalyticsSettings);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (facebookPixelSettings_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FacebookPixelSettings);
      }
      if (googleAnalyticsSettings_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GoogleAnalyticsSettings);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (facebookPixelSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FacebookPixelSettings);
      }
      if (googleAnalyticsSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GoogleAnalyticsSettings);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrackingSettings other) {
      if (other == null) {
        return;
      }
      if (other.facebookPixelSettings_ != null) {
        if (facebookPixelSettings_ == null) {
          FacebookPixelSettings = new global::PassKit.Grpc.FacebookPixelSettings();
        }
        FacebookPixelSettings.MergeFrom(other.FacebookPixelSettings);
      }
      if (other.googleAnalyticsSettings_ != null) {
        if (googleAnalyticsSettings_ == null) {
          GoogleAnalyticsSettings = new global::PassKit.Grpc.GoogleAnalyticsSettings();
        }
        GoogleAnalyticsSettings.MergeFrom(other.GoogleAnalyticsSettings);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (facebookPixelSettings_ == null) {
              FacebookPixelSettings = new global::PassKit.Grpc.FacebookPixelSettings();
            }
            input.ReadMessage(FacebookPixelSettings);
            break;
          }
          case 18: {
            if (googleAnalyticsSettings_ == null) {
              GoogleAnalyticsSettings = new global::PassKit.Grpc.GoogleAnalyticsSettings();
            }
            input.ReadMessage(GoogleAnalyticsSettings);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (facebookPixelSettings_ == null) {
              FacebookPixelSettings = new global::PassKit.Grpc.FacebookPixelSettings();
            }
            input.ReadMessage(FacebookPixelSettings);
            break;
          }
          case 18: {
            if (googleAnalyticsSettings_ == null) {
              GoogleAnalyticsSettings = new global::PassKit.Grpc.GoogleAnalyticsSettings();
            }
            input.ReadMessage(GoogleAnalyticsSettings);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
