// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: io/raw/a_rpc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PassKit.Grpc.Raw {

  /// <summary>Holder for reflection information generated from io/raw/a_rpc.proto</summary>
  public static partial class ARpcReflection {

    #region Descriptor
    /// <summary>File descriptor for io/raw/a_rpc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ARpcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJpby9yYXcvYV9ycGMucHJvdG8SA3JhdxobZ29vZ2xlL3Byb3RvYnVmL2Vt",
            "cHR5LnByb3RvGhxnb29nbGUvYXBpL2Fubm90YXRpb25zLnByb3RvGh5pby9j",
            "b21tb24vY29tbW9uX29iamVjdHMucHJvdG8aFGlvL3Jhdy9wcm9qZWN0LnBy",
            "b3RvGhFpby9yYXcvcGFzcy5wcm90bxoucHJvdG9jLWdlbi1vcGVuYXBpdjIv",
            "b3B0aW9ucy9hbm5vdGF0aW9ucy5wcm90bzLbDwoDUmF3En8KEWNyZWF0ZVBh",
            "c3NQcm9qZWN0EhAucmF3LlBhc3NQcm9qZWN0GgYuaW8uSWQiUILT5JMCFSIQ",
            "L3Jhdy9wYXNzUHJvamVjdDoBKpJBMgoDUmF3EhNDcmVhdGUgUGFzcyBQcm9q",
            "ZWN0GhZDcmVhdGVzIGEgUGFzcyBQcm9qZWN0EpMBChF1cGRhdGVQYXNzUHJv",
            "amVjdBIQLnJhdy5QYXNzUHJvamVjdBoQLnJhdy5QYXNzUHJvamVjdCJagtPk",
            "kwIVGhAvcmF3L3Bhc3NQcm9qZWN0OgEqkkE8CgNSYXcSE1VwZGF0ZSBQYXNz",
            "IFByb2plY3QaIFVwZGF0ZXMgYW4gZXhpc3RpbmcgUGFzcyBQcm9qZWN0EoIB",
            "Cg5nZXRQYXNzUHJvamVjdBIGLmlvLklkGhAucmF3LlBhc3NQcm9qZWN0IlaC",
            "0+STAhcSFS9yYXcvcGFzc1Byb2plY3Qve2lkfZJBNgoDUmF3EhBHZXQgUGFz",
            "cyBQcm9qZWN0Gh1HZXRzIGFuIGV4aXN0aW5nIFBhc3MgUHJvamVjdBKUAQoP",
            "Y29weVBhc3NQcm9qZWN0EhsucmF3LlBhc3NQcm9qZWN0Q29weVJlcXVlc3Qa",
            "Bi5pby5JZCJcgtPkkwIaIhUvcmF3L3Bhc3NQcm9qZWN0L2NvcHk6ASqSQTkK",
            "A1JhdxIRQ29weSBQYXNzIFByb2plY3QaH0NvcGllcyBhbiBleGlzdGluZyBQ",
            "YXNzIFByb2plY3QShwIKEWRlbGV0ZVBhc3NQcm9qZWN0EgYuaW8uSWQaFi5n",
            "b29nbGUucHJvdG9idWYuRW1wdHki0QGC0+STAhoqFS9yYXcvcGFzc1Byb2pl",
            "Y3Qve2lkfToBKpJBrQEKA1JhdxITRGVsZXRlIFBhc3MgUHJvamVjdBqQAURl",
            "bGV0ZXMgYW4gZXhpc3RpbmcgUGFzcyBQcm9qZWN0IGJ5IGlkLiBEZWxldGlu",
            "ZyBhIFBhc3MgUHJvamVjdCByZXN1bHRzIGluIGFsbCBwYXNzZXMgYmVpbmcg",
            "aW52YWxpZGF0ZWQgYW5kIHJlbW92ZWQuIE5lZWRzIHRvIGJlIHVzZWQgd2l0",
            "aCBjYXJlLhJlCgpjcmVhdGVQYXNzEgkucmF3LlBhc3MaBi5pby5JZCJEgtPk",
            "kwIOIgkvcmF3L3Bhc3M6ASqSQS0KA1JhdxILQ3JlYXRlIFBhc3MaGUNyZWF0",
            "ZXMgYSBuZXcgUGFzcyByZWNvcmQSawoKdXBkYXRlUGFzcxIJLnJhdy5QYXNz",
            "GgYuaW8uSWQiSoLT5JMCDhoJL3Jhdy9wYXNzOgEqkkEzCgNSYXcSC1VwZGF0",
            "ZSBQYXNzGh9VcGRhdGVzIGFuIGV4aXN0aW5nIFBhc3MgcmVjb3JkEpIBChFz",
            "dHJlYW1QYXNzVXBkYXRlcxIJLnJhdy5QYXNzGgYuaW8uSWQiZpJBYwoDUmF3",
            "EjJTdHJlYW0gUGFzcyBVcGRhdGVzIChvZmZpY2lhbCBTREsncyBvbmx5LCBu",
            "byBSRVNUKRooVXBkYXRlcyBleGlzdGluZyBQYXNzIHJlY29yZHMgdmlhIHN0",
            "cmVhbSgBMAESZAoLZ2V0UGFzc0J5SWQSBi5pby5JZBoJLnJhdy5QYXNzIkKC",
            "0+STAhASDi9yYXcvcGFzcy97aWR9kkEpCgNSYXcSDkdldCBQYXNzIGJ5IElE",
            "GhJHZXRzIGEgcGFzcyByZWNvcmQSwwEKE2dldFBhc3NCeUV4dGVybmFsSWQS",
            "Ii5yYXcuUGFzc1JlY29yZEJ5RXh0ZXJuYWxJZFJlcXVlc3QaCS5yYXcuUGFz",
            "cyJ9gtPkkwIzEjEvcmF3L3Bhc3MvZXh0ZXJuYWxJZC97cGFzc1Byb2plY3RJ",
            "ZH0ve2V4dGVybmFsSWR9kkFBCgNSYXcSF0dldCBQYXNzIGJ5IEV4dGVybmFs",
            "IElEGiFHZXRzIGEgcGFzcyByZWNvcmQgYnkgRXh0ZXJuYWwgSUQSdgoKZGVs",
            "ZXRlUGFzcxIJLnJhdy5QYXNzGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IkWC",
            "0+STAhMqDi9yYXcvcGFzcy97aWR9OgEqkkEpCgNSYXcSC0RlbGV0ZSBQYXNz",
            "GhVEZWxldGVzIGEgcGFzcyByZWNvcmQSwAEKF2xpc3RQYXNzZXNCeVBhc3NQ",
            "cm9qZWN0EiMucmF3Lkxpc3RQYXNzZXNCeVBhc3NQcm9qZWN0UmVxdWVzdBoJ",
            "LnJhdy5QYXNzInOC0+STAiAiGy9yYXcvcGFzcy9saXN0QnlQYXNzUHJvamVj",
            "dDoBKpJBSgoDUmF3EgtMaXN0IFBhc3Nlcxo2TGlzdCBhbGwgcGFzc2VzIGZv",
            "ciBwYXNzIHByb2plY3QuIFN1cHBvcnRzIHBhZ2luYXRpb24uMAESxgEKGGxp",
            "c3RQYXNzZXNCeVBhc3NUZW1wbGF0ZRIkLnJhdy5MaXN0UGFzc2VzQnlQYXNz",
            "VGVtcGxhdGVSZXF1ZXN0GgkucmF3LlBhc3Mid4LT5JMCISIcL3Jhdy9wYXNz",
            "L2xpc3RCeVBhc3NUZW1wbGF0ZToBKpJBTQoDUmF3EgtMaXN0IFBhc3Nlcxo5",
            "TGlzdCBhbGwgcGFzc2VzIGZvciBhIHBhc3MgdGVtcGxhdGUuIFN1cHBvcnRz",
            "IHBhZ2luYXRpb24uMAFCigcKFGNvbS5wYXNza2l0LmdycGMuUmF3WihzdGFz",
            "aC5wYXNza2l0LmNvbS9pby9tb2RlbC9zZGsvZ28vaW8vcmF3qgIQUGFzc0tp",
            "dC5HcnBjLlJhd5JBswYSwAIKFlBhc3NLaXQgUmF3IFBhc3NlcyBBUEkSpQFU",
            "aGlzIHByb3RvY29sIGlzIHN1aXQgZm9yIGNhc2VzIHdoZXJlIHRoZSBidXNp",
            "bmVzcyBsb2dpYyBpcyBoYW5kbGVkIGVsc2V3aGVyZSwgYW5kIHRoZSBwdXJw",
            "b3NlIGlzIHB1cmVseSB0byBpc3N1ZSBhbmQgdXBkYXRlIGNvbnRlbnQgZm9y",
            "IEFwcGxlIFdhbGxldCBhbmQgR29vZ2xlIFBheS4aOGh0dHBzOi8vcGFzc2tp",
            "dC5jb20vbGVnYWwvdGVybXMtb2Ytc3Vic2NyaXB0aW9uLXNlcnZpY2UvIj8K",
            "D1Bhc3NLaXQgU3VwcG9ydBIXaHR0cHM6Ly9kb2NzLnBhc3NraXQuaW8aE3N1",
            "cHBvcnRAcGFzc2tpdC5jb20yAzAuMSoBAjIQYXBwbGljYXRpb24vanNvbjoQ",
            "YXBwbGljYXRpb24vanNvblI5CgMyMDASMgooUmV0dXJuZWQgd2hlbiB0aGUg",
            "cmVxdWVzdCBpcyBzdWNjZXNzZnVsLhIGCgSaAgEHUjQKAzQwMBItCitSZXR1",
            "cm5lZCB3aGVuIHdyb25nIHVzZXIgaW5wdXQgaXMgcHJvdmlkZWQuUjAKAzQw",
            "MRIpCidSZXR1cm5lZCB3aGVuIHRoZSB1c2VyIGlzIHVuYXV0aG9yaXplZC5S",
            "UAoDNDAzEkkKR1JldHVybmVkIHdoZW4gdGhlIHVzZXIgZG9lcyBub3QgaGF2",
            "ZSBwZXJtaXNzaW9uIHRvIGFjY2VzcyB0aGUgcmVzb3VyY2UuUjsKAzQwNBI0",
            "CipSZXR1cm5lZCB3aGVuIHRoZSByZXNvdXJjZSBkb2VzIG5vdCBleGlzdC4S",
            "BgoEmgIBB1I8CgM1MDASNQorUmV0dXJuZWQgd2hlbiB0aGVyZSBpcyBhbiB1",
            "bmV4cGVjdGVkIGVycm9yLhIGCgSaAgEHUlcKAzUwMxJQCk5TZXJ2ZXIgaXMg",
            "dW5hdmFpbGFibGUuIEJhY2sgb2ZmIGZvciAyNTBtcyBhbmQgcmVwZWF0IHJl",
            "cXVlc3QgdW50aWwgc3VjY2Vzc2Z1bC5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, global::PassKit.Grpc.CommonObjectsReflection.Descriptor, global::PassKit.Grpc.Raw.ProjectReflection.Descriptor, global::PassKit.Grpc.Raw.PassReflection.Descriptor, global::PassKit.Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
